

export let objStrApi={};
objStrApi.depPicture="https://ber.berlin-airport.de/etc.clientlibs/restartweb/clientlibs/clientlib-site/resources/img/icon-departure.svg"  ;
objStrApi.arrPicture="https://ber.berlin-airport.de/etc.clientlibs/restartweb/clientlibs/clientlib-site/resources/img/icon-arrival.svg" ;

objStrApi.Ya="https://yandex.ru/images/search?size=large&iorient=horizontal&text=";
objStrApi.gugl="https://www.googleapis.com/customsearch/v1/?cx=e57c53fa1fb4f9610&key=AIzaSyA7Q7EkvvM-yfHIlVN9p6wPw44esI6WPBk&"+
"filetype=jpg&imgSize=medium&imgType=photo&searchType=image"+
"&q=";
//&siteSearch=jetphotos.com
objStrApi.arr_cityPhotoBased="https://phonoteka.org/uploads/posts/2021-05/thumbs/1621588230_15-phonoteka_org-p-fon-komiks-gorod-17.png";
objStrApi.vehiclePhotoBased="https://www.usglobaletfs.com/wp-content/uploads/2018/09/jet-purple-sky.jpg";


objStrApi.pixabay="https://pixabay.com/api/?key=19899502-e9071bae7fc3a2d3a4810e915&"+
"image_type=photo&category=buildings&orientation=horizontal&min_width=640&min_height=480&q=";

objStrApi.flickr="https://www.flickr.com/services/rest/?method=flickr.photos.search&api_key=65af447c7202f38afd0afd342d6c35c3&"+
"format=json&nojsoncallback=1&content_type=1&media=photos&text=" ;

objStrApi.cors="https://cors.eu.org/" ;
objStrApi.AirLabs="https://airlabs.co/api/v9/schedules?api_key=449374fa-487f-4246-9359-395f326383c2&dep_iata=TLV";



objStrApi.Yandex=
`https://api.rasp.yandex.net/v3.0/schedule/?apikey=1e2ea5a3-6bac-40c8-b3ad-e578706f9c4a
&transport_types=plane&system=iata&offset=0&limit=200` ;



objStrApi.city={
  FMM : 'Memmingen' ,
  FKB : 'Baden (Karlsruhe)' ,
  AER : 'Sochi',
  KRR : 'Krasnodar' ,
  U6  : 'Ural Airlines',
  DWC : 'Dubai' ,
  ETM : 'Eilat' ,
  JAA	:	'Jalalabad',
  KBL	:	'Kabul - Khwaja Rawash Airport',
  URZ	:	'Uruzgan',
  TIA	:	'Tirana - Rinas',
  ALG	:	'Algiers, Houari Boumediene Airport',
  AAE	:	'Annaba',
  CZL	:	'Constantine',
  GJL	:	'Jijel',
  ORN	:	'Oran (Ouahran)',
  PPG	:	'Pago Pago',
  ALV	:	'Andorra La Vella - Heliport',
  BUG	:	'Benguela',
  CAB	:	'Cabinda',
  JMB	:	'Jamba',
  LAD	:	'Luanda - 4 de Fevereiro',
  UGO	:	'Uige',
  AXA	:	'Anguilla',
  ANU	:	'Antigua, V.C. Bird International',
  BUE	:	'Buenos Aires',
  EZE	:	'Buenos Aires, Ezeiza International Airport',
  AEP	:	'Buenos Aires, Jorge Newbery',
  COR	:	'Cordoba',
  IGR	:	'Iguazu, Cataratas',
  JSM	:	'Jose De San Martin',
  JUJ	:	'Jujuy - El Cadillal Airport',
  JNI	:	'Junin',
  MDQ	:	'Mar del Plata',
  MDZ	:	'Mendoza',
  ROS	:	'Rosario',
  SLA	:	'Salta, Gen Belgrano',
  BRC	:	'San Carlos de Bariloche',
  RSA	:	'Santa Rosa',
  USH	:	'Ushuaia - Islas Malvinas Airport',
  EVN	:	'Eriwan (Yerevan, Jerevan)',
  AUA	:	'Aruba - Reina Beatrix International, Oranjestad',
  AUA	:	'Oranjestad - Reina Beatrix International',
  ADL	:	'Adelaide',
  ALH	:	'Albany',
  ABX	:	'Albury',
  ASP	:	'Alice Springs',
  AYQ	:	'Ayers Rock - Connellan',
  AYR	:	'Ayr',
  BNK	:	'Ballina',
  ABM	:	'Bamaga',
  BLT	:	'Blackwater',
  ZBO	:	'Bowen',
  BMP	:	'Brampton Island',
  BNE	:	'Brisbane',
  BHQ	:	'Broken Hill',
  BME	:	'Broome',
  BDB	:	'Bundaberg',
  BWT	:	'Burnie (Wynyard)',
  CNS	:	'Cairns',
  CBR	:	'Canberra - Canberra Airport',
  CVQ	:	'Carnarvon',
  CSI	:	'Casino',
  CED	:	'Ceduna',
  CES	:	'Cessnock',
  CXT	:	'Charters Towers',
  CMQ	:	'Clermont',
  CFS	:	'Coffs Harbour',
  KCE	:	'Collinsville',
  CPD	:	'Coober Pedy',
  CTN	:	'Cooktown',
  OOM	:	'Cooma',
  DBY	:	'Dalby',
  DRW	:	'Darwin',
  DDI	:	'Daydream Island',
  DRB	:	'Derby',
  DPO	:	'Devonport',
  DBO	:	'Dubbo',
  DKI	:	'Dunk Island',
  DYA	:	'Dysart',
  EDR	:	'Emerald',
  EMD	:	'Emerald',
  EPR	:	'Esperance',
  GEX	:	'Geelong',
  GET	:	'Geraldton',
  GLT	:	'Gladstone',
  OOL	:	'Gold Coast',
  GOO	:	'Goondiwindi',
  GOV	:	'Gove (Nhulunbuy)',
  GKL	:	'Great Keppel Island',
  GFF	:	'Griffith',
  GTE	:	'Groote Eylandt - Alyangula',
  GYP	:	'Gympie',
  HLT	:	'Hamilton',
  HTI	:	'Hamilton Island',
  HIS	:	'Hayman Island',
  HVB	:	'Hervey Bay',
  HNK	:	'Hinchinbrook Island',
  HBA	:	'Hobart',
  HMH	:	'Home Hill',
  IGH	:	'Ingham',
  IFL	:	'Innisfail',
  JAD	:	'Jandakot',
  JCK	:	'Julia Creek',
  JUN	:	'Jundah',
  KGI	:	'Kalgoorlie',
  KTA	:	'Karratha',
  KRB	:	'Karumba',
  KTR	:	'Katherine',
  KGC	:	'Kingscote',
  KWM	:	'Kowanyama',
  KNX	:	'Kununurra',
  LST	:	'Launceston',
  LVO	:	'Laverton',
  LEA	:	'Learmouth (Exmouth)',
  LER	:	'Leinster',
  LNO	:	'Leonora',
  LDC	:	'Lindeman Island',
  LSY	:	'Lismore',
  LZR	:	'Lizard Island',
  IRG	:	'Lockhart River',
  LRE	:	'Longreach',
  MKY	:	'Mackay',
  MTL	:	'Maitland',
  MBH	:	'Maryborough',
  MKR	:	'Meekatharra',
  MEL	:	'Melbourne - Melbourne Airport (Tullamarine)',
  MIM	:	'Merimbula',
  MMM	:	'Middlemount',
  MQL	:	'Mildura',
  MOV	:	'Moranbah',
  MRZ	:	'Moree',
  MYA	:	'Moruya',
  MGB	:	'Mount Gambier',
  MMG	:	'Mount Magnet',
  ISA	:	'Mt. Isa',
  NAA	:	'Narrabri',
  NRA	:	'Narrandera',
  BEO	:	'Newcastle - Belmont',
  NTL	:	'Newcastle - Williamtown',
  ZNE	:	'Newman',
  NSA	:	'Noosa',
  NLK	:	'Norfolk Island',
  OLP	:	'Olympic Dam',
  OAG	:	'Orange',
  ORS	:	'Orpheus Island',
  PBO	:	'Paraburdoo',
  PER	:	'Perth International',
  PUG	:	'Port Augusta',
  PHE	:	'Port Hedland',
  PTJ	:	'Portland',
  PLO	:	'Port Lincoln',
  PQQ	:	'Port Macquarie',
  PPP	:	'Prosperpine',
  UEE	:	'Queenstown',
  ROK	:	'Rockhampton',
  NSO	:	'Scone',
  JHQ	:	'Shute Harbour',
  SIX	:	'Singleton',
  SOI	:	'South Molle Island',
  KBY	:	'Streaky Bay',
  MCY	:	'Sunshine Coast',
  SYD	:	'Sydney - Sydney Airport',
  TMW	:	'Tamworth',
  TRO	:	'Taree',
  TEM	:	'Temora',
  TCA	:	'Tennant Creek',
  TIS	:	'Thursday Island',
  TPR	:	'Tom Price',
  TWB	:	'Toowoomba',
  TSV	:	'Townsville',
  WGA	:	'Wagga',
  WMB	:	'Warrnambool',
  WEI	:	'Weipa',
  HAP	:	'Whitsunday Resort',
  WYA	:	'Whyalla',
  WHM	:	'Wickham',
  WUN	:	'Wiluna',
  WOL	:	'Wollongong',
  UMR	:	'Woomera',
  WYN	:	'Wyndham',
  GRZ	:	'Graz',
  INN	:	'Innsbruck - Kranebitten',
  KLU	:	'Klagenfurt',
  LNZ	:	'Linz - Hoersching',
  SZG	:	'Salzburg - W.A. Mozart',
  VIE	:	'Vienna - Vienna International',
  BAK	:	'Baku - Heydar Aliyev International Airport',
  NAJ	:	'Nakhichevan',
  CCZ	:	'Chub Cay',
  FPO	:	'Freeport - Grand Bahama International Airport',
  GHB	:	'Govenors Harbour',
  FPO	:	'Grand Bahama International',
  MHH	:	'Marsh Harbour',
  NAS	:	'Nassau',
  ELH	:	'North Eleuthera',
  RSD	:	'Rock Sound',
  ZSA	:	'San Salvador',
  TCB	:	'Treasure Cay',
  BAH	:	'Bahrain - Bahrain International Airport',
  BZL	:	'Barisal',
  CGP	:	'Chittagong',
  DAC	:	'Dhaka - Zia International Airport',
  JSR	:	'Jessore - Jessore Airport',
  ZYL	:	'Sylhet',
  BGI	:	'Bridgetown - Grantley Adams International',
  MSQ	:	'Minsk, International',
  ANR	:	'Antwerp',
  BRU	:	'Brussels - Brussels Airport',
  GNE	:	'Ghent (Gent)',
  LGG	:	'Liege',
  BZE	:	'Belize City - Philip S.W.Goldson International',
  COO	:	'Cotonou - Cotonou Cadjehoun Airport',
  BDA	:	'Bermuda - L.F. Wade International Airport',
  PBH	:	'Paro',
  CBB	:	'Cochabamba',
  LPB	:	'La Paz - El Alto',
  SRZ	:	'Santa Cruz de la Sierra',
  SRB	:	'Santa Rosa',
  OMO	:	'Mostar',
  SJJ	:	'Sarajevo',
  FRW	:	'Francistown',
  GBE	:	'Gaborone - Sir Seretse Khama International Airport',
  JWA	:	'Jwaneng',
  MUB	:	'Maun',
  PKW	:	'Selibi Phikwe',
  AJU	:	'Aracaju',
  BEL	:	'Belem - Val de Cans International Airport',
  CNF	:	'Belo Horizonte - Tancredo Neves International Airport',
  BVB	:	'Boa Vista',
  BSB	:	'Brasilia - President Juscelino Kubitschek International',
  CGR	:	'Campo Grande',
  CGB	:	'Cuiaba - Marechal Rondon International Airport',
  CWB	:	'Curitiba - Afonso Pena International Airport',
  FLN	:	'Florianopolis',
  FOR	:	'Fortaleza - Pinto Martins Airport',
  GYN	:	'Goiania, Santa Genoveva Airport',
  GRU	:	'Sao Paulo - Guarulhos International',
  JCM	:	'Jacobina',
  JLS	:	'Jales',
  JNA	:	'Januaria',
  JTI	:	'Jatai',
  JCB	:	'Joacaba',
  JPA	:	'Joao Pessoa - Castro Pinto Airport',
  JOI	:	'Joinville - Cubatao Airport',
  JDF	:	'Juiz De Fora - Francisco De Assis Airport',
  MCP	:	'Macapa - Alberto Alcolumbre International Airport',
  MCZ	:	'Maceio - Zumbi dos Palmares International Airport',
  MAO	:	'Manaus - Eduardo Gomes International Airport',
  QGF	:	'Montenegro',
  NAT	:	'Natal - Augusto Severo International Airport',
  PMW	:	'Palmas',
  POA	:	'Porto Alegre - Salgado Filho International Airport',
  PVH	:	'Porto Velho',
  REC	:	'Recife - Guararapes-Gilberto Freyre International',
  RBR	:	'Rio Branco - Plácido de Castro International Airport',
  GIG	:	'Rio de Janeiro - Galeao',
  SDU	:	'Rio de Janeiro - Santos Dumont',
  RIO	:	'Rio de Janeiro',
  SSA	:	'Salvador - Salvador International Airport',
  SRA	:	'Santa Rosa',
  SLZ	:	'Sao Luis - Marechal Cunha Machado International',
  SAO	:	'Sao Paulo',
  CGH	:	'Sao Paulo - Congonhas',
  GRU	:	'Sao Paulo - Guarulhos',
  VCP	:	'Sao Paulo - Viracopos',
  THE	:	'Teresina',
  UBA	:	'Uberaba',
  UDI	:	'Uberlandia - Eduardo Gomes Airport',
  URB	:	'Urubupunga - Ernesto Pochler Airport',
  URG	:	'Uruguaiana - Ruben Berta Airport',
  VIX	:	'Vitoria - Eurico de Aguiar Salles Airport',
  TOV	:	'Tortola',
  BWN	:	'Bandar Seri Begawan - Brunei International Airport',
  BOJ	:	'Bourgas/Burgas',
  GOZ	:	'Gorna',
  JAM	:	'Jambol',
  ROU	:	'Ruse',
  SLS	:	'Silistra',
  SOF	:	'Sofia - Vrazhdebna',
  TGV	:	'Targovishte',
  VAR	:	'Varna',
  VID	:	'Vidin',
  BOY	:	'Bobo/Dioulasso',
  OUA	:	'Ouagadougou',
  BJM	:	'Bujumbura - Bujumbura International Airport',
  PNH	:	'Phnom Penh - Pochentong',
  DLA	:	'Douala',
  GOU	:	'Garoua',
  MVR	:	'Maroua',
  NGE	:	'N_Gaoundere',
  YAO	:	'Yaounde',
  YAT	:	'Attawapiskat, NT',
  YVB	:	'Bonaventure, PQ',
  YYC	:	'Calgary - Calgary International Airport',
  YCB	:	'Cambridge Bay',
  YYQ	:	'Churchill',
  YDF	:	'Deer Lake/Corner Brook',
  YEA	:	'Edmonton',
  YEG	:	'Edmonton, International',
  YXD	:	'Edmonton, Municipal',
  YFO	:	'Flin Flon',
  YFA	:	'Fort Albert',
  YMM	:	'Fort McMurray',
  YSM	:	'Fort Smith',
  YXJ	:	'Fort St. John',
  YFC	:	'Fredericton',
  YQX	:	'Gander',
  YGX	:	'Gillam',
  YYR	:	'Goose Bay',
  YHZ	:	'Halifax International',
  YUX	:	'Hall Beach',
  YHM	:	'Hamilton',
  YHR	:	'Harrington Harbour, PQ',
  YEV	:	'Inuvik',
  YFB	:	'Iqaluit (Frobisher Bay)',
  YKA	:	'Kamloops, BC',
  ZKE	:	'Kaschechawan, PQ',
  YLW	:	'Kelowna, BC',
  YVP	:	'Kuujjuaq (FortChimo)',
  YGW	:	'Kuujjuarapik',
  XLB	:	'Lac Brochet, MB',
  YGL	:	'La Grande',
  YLR	:	'Leaf Rapids',
  YXU	:	'London',
  YQM	:	'Moncton',
  YMQ	:	'Montreal',
  YUL	:	'Montreal - Dorval (Montréal-Trudeau)',
  YMX	:	'Montreal - Mirabel',
  YSR	:	'Nanisivik',
  YVQ	:	'Norman Wells',
  YOW	:	'Ottawa - Hull',
  YPN	:	'Port Menier, PQ',
  YXS	:	'Prince George',
  YPR	:	'Prince Rupert/Digby Island',
  XPK	:	'Pukatawagan',
  YQB	:	'Quebec - Quebec International',
  YOP	:	'Rainbow Lake, AB',
  YQR	:	'Regina',
  YRB	:	'Resolute Bay',
  YSJ	:	'Saint John',
  YZP	:	'Sandspit',
  YXE	:	'Saskatoon',
  ZTM	:	'Shamattawa, MB',
  YYD	:	'Smithers',
  XSI	:	'South Indian Lake, MB',
  YIF	:	'St. Augustin, PQ',
  YYT	:	'St. John_s',
  FSP	:	'St. Pierre, NF',
  YXT	:	'Terrace',
  YQD	:	'The Pas',
  YTH	:	'Thompson',
  YQT	:	'Thunder Bay',
  YTZ	:	'Toronto - Billy Bishop Toronto City Airport',
  YYZ	:	'Toronto - Toronto Pearson International Airport',
  YTO	:	'Toronto',
  YUD	:	'Umiujaq',
  YBE	:	'Uranium City',
  YVO	:	'Val d_Or',
  YVR	:	'Vancouver - Vancouver International',
  YYJ	:	'Victoria',
  YWK	:	'Wabush',
  YXN	:	'Whale Cove, NT',
  YXY	:	'Whitehorse',
  YQG	:	'Windsor Ontario',
  YWG	:	'Winnipeg International',
  YZF	:	'Yellowknife',
  RAI	:	'Praia - Nelson Mandela International Airport',
  SID	:	'Sal',
  GCM	:	'Grand Cayman - Owen Roberts International',
  BBY	:	'Bambari',
  BGU	:	'Bangassou',
  BGF	:	'Bangui - M_Poko International Airport',
  BBT	:	'Berberati',
  IRO	:	'Biraro',
  BIV	:	'Bria',
  CRF	:	'Carnot',
  ODA	:	'Ouadda',
  AEH	:	'Abeche',
  MQQ	:	'Moundou',
  NDJ	:	'N_Djamena',
  ACI	:	'Alderney',
  GCI	:	'Guernsey',
  JER	:	'Jersey',
  CJC	:	'Calama - El Loa',
  IPC	:	'Easter Island',
  PUQ	:	'Punta Arenas - Presidente Carlos Ibáñez del Campo',
  SCL	:	'Santiago de Chile - Arturo Merino Benitez',
  VAP	:	'Valparaiso',
  PEK	:	'Beijing',
  NAY	:	'Beijing - Nanyuan Airport',
  SHA	:	'Shanghai - Hongqiao',
  PVG	:	'Shanghai - Pu Dong',
  TSN	:	'Tianjin',
  BAQ	:	'Barranquilla',
  BOG	:	'Bogota - El Nuevo Dorado International Airport',
  BGA	:	'Bucaramanga',
  CLO	:	'Cali',
  CTG	:	'Cartagena - Rafael Núñez International Airport',
  MDE	:	'Medellin - José María Córdova International',
  PEI	:	'Pereira',
  ADZ	:	'San Andres',
  SSL	:	'Santa Rosalia',
  AJN	:	'Anjouan - Anjouan Airport',
  HAH	:	'Moroni - Prince Said Ibrahim',
  FIH	:	'Kinshasa - N_Djili',
  FKI	:	'Kisangani',
  LIQ	:	'Lisala',
  FBM	:	'Lumbumbashi',
  BZV	:	'Brazzaville - Maya-Maya Airport',
  PNR	:	'Pointe Noire',
  RAR	:	'Rarotonga',
  SJO	:	'San Jose',
  UPL	:	'Upala',
  ABJ	:	'Abidjan',
  BYK	:	'Bouake',
  DJO	:	'Daloa',
  HGO	:	'Korhogo',
  MJC	:	'Man',
  SPY	:	'San Pedro',
  ZSS	:	'Sassandra',
  ASK	:	'Yamoussoukro',
  DBV	:	'Dubrovnik',
  LSZ	:	'Losinj - Losinj Arpt',
  OSI	:	'Osijek',
  PUY	:	'Pula',
  RJK	:	'Rijeka',
  SPU	:	'Split',
  ZAD	:	'Zadar',
  ZAG	:	'Zagreb - Zagreb Airport Pleso',
  CFG	:	'Cienfuegos - Jaime González Airport',
  HAV	:	'Havana - José Martí International',
  HOG	:	'Holguin',
  SCU	:	'Santiago - Antonio Maceo Airport',
  VRA	:	'Varadero',
  AKT	:	'Akrotiri - RAF',
  LCA	:	'Larnaca',
  QLI	:	'Limassol',
  NIC	:	'Nicosia',
  PFO	:	'Paphos',
  PRG	:	'Prague - Václav Havel Airport (formerly Ruzyne)',
  UHE	:	'Uherske Hradiste',
  AAR	:	'Aarhus',
  AAL	:	'Alborg',
  BLL	:	'Billund',
  CPH	:	'Copenhagen - Copenhagen Airport',
  EBJ	:	'Esbjerg',
  FAE	:	'Faroer - Vágar Airport',
  KRP	:	'Karup',
  ODE	:	'Odense',
  RNN	:	'Roenne',
  SKS	:	'Skrydstrup',
  SGD	:	'Soenderborg',
  TED	:	'Thisted',
  JIB	:	'Djibouti (city) - Djibouti-Ambouli International Airport',
  DOM	:	'Melville Hall',
  LRM	:	'Casa de Campo - La Romana International Airport',
  AZS	:	'Samana - Samaná El Catey International Airport',
  POP	:	'Puerto Plata',
  PUJ	:	'Punta Cana - Punta Cana International',
  SDQ	:	'Santo Domingo',
  GYE	:	'Guayaquil - Simon Bolivar',
  JIP	:	'Jipijapa',
  UIO	:	'Quito - Mariscal Sucre International Airport',
  SNC	:	'Salinas',
  AUE	:	'Abu Rudeis',
  ABS	:	'Abu Simbel',
  AAC	:	'Al Arish',
  HBH	:	'Alexandria - Borg el Arab Airport',
  ALY	:	'Alexandria - El Nhouza Airport',
  ATZ	:	'Assiut',
  ASW	:	'Aswan - Daraw Airport',
  CAI	:	'Cairo - Cairo International Airport',
  EMY	:	'El Minya',
  HRG	:	'Hurghada International',
  UVL	:	'Kharga - New Valley',
  LXR	:	'Luxor',
  RMF	:	'Marsa Alam',
  MUH	:	'Marsa Matrah (Marsa Matruh)',
  UVL	:	'New Valley - Kharga',
  PSD	:	'Port Said',
  SKV	:	'Santa Katarina - Mount Sinai',
  SSH	:	'Sharm El Sheikh',
  SEW	:	'Siwa',
  SAL	:	'San Salvador',
  SSG	:	'Malabo - Malabo International Airport',
  ASM	:	'Asmara - Asmara International',
  QUF	:	'Tallinn - Pirita Harbour',
  TLL	:	'Tallinn - Ulemiste',
  ADD	:	'Addis Ababa - Bole International Airport',
  JIJ	:	'Jijiga',
  JIM	:	'Jimma',
  BCO	:	'Jinka - Baco/Jinka Airport',
  CST	:	'Castaway',
  NAN	:	'Nadi',
  SUV	:	'Suva - Nausori Airport (Luvuluvu)',
  SUV	:	'Nausori',
  ENF	:	'Enontekioe',
  HEL	:	'Helsinki - Vantaa',
  IVL	:	'Ivalo',
  JOE	:	'Joensuu',
  JYV	:	'Jyväskylä (Jyvaskyla)',
  KAJ	:	'Kajaani',
  KHJ	:	'Kauhajoki',
  KEM	:	'Kemi/Tornio',
  KTT	:	'Kittilä',
  KOK	:	'Kokkola/Pietarsaari',
  KUO	:	'Kuopio',
  KAO	:	'Kuusamo',
  LPP	:	'Lappeenranta',
  MHQ	:	'Mariehamn (Maarianhamina)',
  MIK	:	'Mikkeli',
  OUL	:	'Oulu',
  POR	:	'Pori',
  RVN	:	'Rovaniemi',
  SVL	:	'Savonlinna',
  SJY	:	'Seinaejoki',
  SOT	:	'Sodankylae',
  TMP	:	'Tampere',
  TKU	:	'Turku',
  VAA	:	'Vaasa',
  VRK	:	'Varkaus',
  AJA	:	'Ajaccio',
  LBI	:	'Albi',
  NCY	:	'Annecy',
  AUR	:	'Aurillac',
  BIA	:	'Bastia',
  EGC	:	'Bergerac - Roumanieres',
  BIQ	:	'Biarritz',
  BOD	:	'Bordeaux - Bordeaux Airport',
  BES	:	'Brest',
  CLY	:	'Calvi',
  CEQ	:	'Cannes – Mandelieu Airport',
  CMF	:	'Chambery',
  CFE	:	'Clermont Ferrand',
  DNR	:	'Dinard',
  DLP	:	'Disneyland Paris',
  FSC	:	'Figari',
  FRJ	:	'Frejus',
  GNB	:	'Grenoble',
  LRH	:	'La Rochelle',
  LAI	:	'Lannion',
  LIL	:	'Lille - Lille Airport',
  LIG	:	'Limoges',
  LRT	:	'Lorient',
  LDE	:	'Lourdes/Tarbes',
  LYS	:	'Lyon - Lyon-Saint Exupéry Airport official website',
  MRS	:	'Marseille - Marseille Provence Airport',
  MZM	:	'Metz -  Frescaty',
  ETZ	:	'Metz/Nancy Metz-Nancy-Lorraine',
  MPL	:	'Montpellier - Montpellier–Méditerranée Airport',
  MLH	:	'Mulhouse',
  ENC	:	'Nancy',
  NTE	:	'Nantes - Nantes Atlantique Airport',
  NCE	:	'Nice - Cote D_Azur Airport',
  FNI	:	'Nimes',
  PAR	:	'Paris',
  CDG	:	'Paris - Charles de Gaulle',
  LBG	:	'Paris - Le Bourget',
  ORY	:	'Paris - Orly',
  PUF	:	'Pau',
  PGF	:	'Perpignan',
  PIS	:	'Poitiers - Biard',
  UIP	:	'Quimper',
  RNS	:	'Rennes',
  RNE	:	'Roanne',
  RDZ	:	'Rodez',
  SBK	:	'Saint Brieuc',
  EBU	:	'St. Etienne',
  SXB	:	'Strasbourg - Strasbourg Airport',
  TLS	:	'Toulouse - Blagnac Airport',
  CAY	:	'Cayenne - Cayenne-Rochambeau Airport',
  BOB	:	'Bora Bora',
  HUH	:	'Huahine',
  XMH	:	'Manihi',
  MAU	:	'Maupiti',
  MOZ	:	'Moorea',
  RFP	:	'Raiatea',
  RGI	:	'Rangiroa',
  UAH	:	'Ua Huka',
  UAP	:	'Ua Pou',
  PPT	:	'Papeete - Faaa',
  XMN	:	'Xiamen',
  LBQ	:	'Lambarene',
  LBV	:	'Libreville',
  MFF	:	'Moanda',
  MJL	:	'Mouila',
  MVB	:	'Mvengue',
  POG	:	'Port Gentil',
  UVE	:	'Oyem',
  BJL	:	'Banjul - Banjul International Airport (Yundum International)',
  TBS	:	'Tbilisi - Novo Alexeyevka',
  AGB	:	'Augsburg - Augsbur gAirport',
  BYU	:	'Bayreuth - Bindlacher-Berg',
  BER	:	'Berlin',
  SXF	:	'Berlin, Schoenefeld',
  TXL	:	'Berlin, Tegel',
  THF	:	'Berlin, Tempelhof (ceased operating in 2008)',
  BRE	:	'Bremen - Bremen Airport (Flughafen Bremen)',
  CBU	:	'Cottbus - Cottbus-Drewitz Airport',
  CGN	:	'Cologne - Cologne Airport (Flughafen Köln/Bonn)',
  DTM	:	'Dortmund',
  DRS	:	'Dresden - Dresden Airport',
  DUS	:	'Duesseldorf - Düsseldorf International Airport',
  ERF	:	'Erfurt - Erfurt Airport (Flughafen Erfurt)',
  FRA	:	'Frankfurt Main - Frankfurt Airport (Rhein-Main-Flughafen)',
  HHN	:	'Frankfurt Hahn',
  FDH	:	'Friedrichshafen - Bodensee-Airport Friedrichshafen',
  GTI	:	'Guettin',
  HAM	:	'Hamburg - Fuhlsbuettel',
  HAJ	:	'Hannover',
  HOQ	:	'Hof',
  JUI	:	'Juist (island)',
  FKB	:	'Karlsruhe-Baden - Soellingen',
  KEL	:	'Kiel - Holtenau',
  CGN	:	'Köln, Köln/Bonn',
  LEJ	:	'Leipzig',
  MUC	:	'Munich - Franz Josef Strauss',
  FMO	:	'Muenster/Osnabrueck',
  NUE	:	'Nürnberg (Nuremberg)',
  PAD	:	'Paderborn/Lippstadt',
  SCN	:	'Saarbruecken',
  STR	:	'Stuttgart - Echterdingen',
  GWT	:	'Westerland, Sylt Airport',
  WIE	:	'Wiesbaden, Air Base',
  ACC	:	'Accra - Kotoka International Airport',
  GIB	:	'Gibraltar',
  GPA	:	'Araxos',
  ATH	:	'Athens - Elefthérios Venizélos International Airport',
  HEW	:	'Athens, Hellinikon Airport',
  CHQ	:	'Chania',
  JKH	:	'Chios',
  CFU	:	'Corfu',
  HER	:	'Heraklion',
  KLX	:	'Kalamata',
  AOK	:	'Karpathos',
  KVA	:	'Kavalla',
  KGS	:	'Kos',
  JMK	:	'Mykonos',
  MJT	:	'Mytilene (Lesbos)',
  JNX	:	'Naxos - Naxos Airport',
  PVK	:	'Preveza/Lefkas',
  RHO	:	'Rhodos',
  SKG	:	'Saloniki',
  SMI	:	'Samos',
  JSI	:	'Skiathos',
  SKG	:	'Thessaloniki - Makedonia Apt.',
  JTR	:	'Thira',
  ZTH	:	'Zakynthos',
  UAK	:	'Narsarsuaq',
  SFJ	:	'Soendre Stroemfjord',
  JUV	:	'Upernavik - Upernavik Heliport',
  UMD	:	'Uummannaq',
  GND	:	'Grenada - Point Salines Airport also Maurice Bishop',
  PTP	:	'Basse-Terre - Pointe-à-Pitre International Airport',
  PTP	:	'Pointe a Pitre',
  SUM	:	'Agana (Hagåtña)',
  GUM	:	'Guam',
  GUM	:	'Hagåtña - Guam International Airport',
  CAN	:	'Guangzhou (Canton) - Baiyun International Airport',
  SZX	:	'Shenzhen - Shenzhen Bao_an International',
  KWL	:	'Guilin - Liangjiang',
  NNG	:	'Nanning',
  GUA	:	'Guatemala City - La Aurora International Airport',
  CKY	:	'Conakry - Conakry International Airport',
  LEK	:	'Labe',
  BXO	:	'Bissau - Osvaldo Vieiro International Airport',
  GEO	:	'Georgetown - Cheddi Jagan International Airport',
  JAK	:	'Jacmel',
  JEE	:	'Jeremie - Jeremie Airport',
  PAP	:	'Port au Prince',
  HRB	:	'Harbin (Haerbin)',
  SPK	:	'Sapporo',
  OKD	:	'Sapporo - Okadama',
  JUT	:	'Juticalpa',
  RTB	:	'Roatan',
  SAP	:	'San Pedro Sula',
  SDH	:	'Santa Rosa, Copan',
  TGU	:	'Tegucigalpa',
  UII	:	'Utila',
  HKG	:	'Hong Kong - International Airport (HKIA)',
  ZJK	:	'Hong Kong - Chek Lap Kok',
  WUH	:	'Wuhan',
  YIH	:	'Yichang',
  BUD	:	'Budapest - Budapest Ferihegy International Airport',
  IBZ	:	'Ibiza',
  EGS	:	'Egilsstadir',
  REK	:	'Reykjavik - Metropolitan Area',
  KEF	:	'Reykjavik - Keflavik International',
  AMD	:	'Ahmedabad',
  ATQ	:	'Amritsar',
  QNB	:	'Anand',
  IXB	:	'Bagdogra',
  BLR	:	'Bangalore',
  BDQ	:	'Baroda',
  IXG	:	'Belgaum',
  BHO	:	'Bhopal',
  BBI	:	'Bhubaneswar',
  BOM	:	'Bombay (Mumbai) - Chhatrapati Shivaji International',
  CCU	:	'Calcutta (Kolkata) - Netaji Subhas Chandra',
  CCJ	:	'Calicut',
  IXC	:	'Chandigarh - Chandigarh International Airport',
  MAA	:	'Chennai (Madras)',
  COK	:	'Cochin',
  CJB	:	'Coimbatore',
  DEL	:	'Delhi - Indira Gandhi International Airport',
  GOI	:	'Goa',
  GAU	:	'Guwahati',
  HYD	:	'Hyderabad - Rajiv Gandhi International Airport',
  JGB	:	'Jagdalpur',
  JAI	:	'Jaipur - Sanganeer',
  JSA	:	'Jaisalmer',
  JLR	:	'Jalandhar',
  IXJ	:	'Jammu - Satwari',
  JGA	:	'Jamnagar - Govardhanpur',
  IXW	:	'Jamshedpur - Sonari Airport',
  PYB	:	'Jeypore - Jeypore Airport',
  JDH	:	'Jodhpur',
  JRH	:	'Jorhat - Rowriah Airport',
  KNU	:	'Kanpur',
  CCU	:	'Kolkata (Calcutta) - Netaji Subhas Chandra',
  LKO	:	'Lucknow',
  MAA	:	'Madras (Chennai) - Chennai International Airport',
  MYQ	:	'Mysore',
  NAG	:	'Nagpur',
  PAT	:	'Patna',
  RAJ	:	'Rajkot',
  IXR	:	'Ranchi',
  SXR	:	'Srinagar',
  STV	:	'Surat',
  TRV	:	'Thiruvananthapuram',
  TRZ	:	'Tiruchirapally',
  UDR	:	'Udaipur - Dabok Airport',
  VNS	:	'Varanasi',
  PNQ	:	'Pune',
  AYW	:	'Ayawasi',
  BDO	:	'Bandung - Husein Sastranegara International Airport',
  DPS	:	'Denpasar/Bali',
  HLP	:	'Jakarta - Halim Perdana Kusuma',
  JKT	:	'Jakarta - Metropolitan Area',
  CGK	:	'Jakarta - Soekarno-Hatta International',
  DJB	:	'Jambi - Sultan Taha Syarifudn',
  DJJ	:	'Jayapura - Sentani',
  MES	:	'Medan - Polania Int_l (now Soewondo AFB)',
  KNO	:	'Medan - Kualanamu International',
  MDC	:	'Manado',
  SUB	:	'Surabaya - Juanda',
  TOD	:	'Tioman',
  UPG	:	'Ujung Pandang - Hasanudin Airport',
  ABD	:	'Abadan',
  THR	:	'Tehran (Teheran) - Mehrabad',
  OMH	:	'Urmiehm (Orumieh)',
  BGW	:	'Bagdad - Baghdad International Airport',
  BSR	:	'Basra, Basrah',
  KIK	:	'Kirkuk',
  OSM	:	'Mosul',
  ORK	:	'Cork',
  CFN	:	'Donegal (Carrickfin)',
  DUB	:	'Dublin - Dublin International Airport',
  GWY	:	'Galway',
  KIR	:	'Kerry County',
  NOC	:	'Knock',
  SNN	:	'Shannon (Limerick)',
  SXL	:	'Sligo',
  ETH	:	'Elat',
  VDA	:	'Elat, Ovula',
  HFA	:	'Haifa',
  JRS	:	'Jerusalem - Atarot Airport (closed)',
  TLV	:	'Tel Aviv - Ben Gurion International',
  AHO	:	'Alghero Sassari',
  AOI	:	'Ancona - Ancona Falconara Airport',
  BRI	:	'Bari',
  BGY	:	'Bergamo/Milan - Orio Al Serio',
  BLQ	:	'Bologna',
  VBS	:	'Brescia, Montichiari',
  BDS	:	'Brindisi',
  CAG	:	'Cagliari',
  CTA	:	'Catania',
  EBA	:	'Elba Island, Marina Di Campo',
  FLR	:	'Florence (Firenze) - Peretola Airport',
  GOA	:	'Genoa',
  SUF	:	'Lamezia Terme',
  LMP	:	'Lampedusa',
  MIL	:	'Milan',
  LIN	:	'Milan - Linate',
  MXP	:	'Milan - Malpensa',
  BGY	:	'Milan - Orio Al Serio',
  NAP	:	'Naples - Naples Capodichino Airport',
  OLB	:	'Olbia',
  PMO	:	'Palermo - Punta Raisi',
  PNL	:	'Pantelleria',
  PEG	:	'Perugia',
  PSR	:	'Pescara',
  PSA	:	'Pisa - Galileo Galilei',
  REG	:	'Reggio Calabria',
  RMI	:	'Rimini',
  ROM	:	'Rome',
  CIA	:	'Rome - Ciampino',
  FCO	:	'Rome - Fuimicino',
  TPS	:	'Trapani',
  TSF	:	'Treviso',
  TRS	:	'Trieste',
  TRN	:	'Turin',
  VCE	:	'Venice - Marco Polo',
  VBS	:	'Verona (Brescia) Montichiari',
  VRN	:	'Verona',
  KIN	:	'Kingston - Norman Manley',
  MBJ	:	'Montego Bay - Sangster International',
  AXT	:	'Akita',
  ASJ	:	'Amami',
  AOJ	:	'Aomori',
  QCB	:	'Chiba City',
  CTS	:	'Sapporo - New Chitose Airport',
  FUK	:	'Fukuoka',
  FKS	:	'Fukushima - Fukushima Airport',
  HAC	:	'Hachijo Jima',
  HKD	:	'Hakodate',
  HIJ	:	'Hiroshima International',
  ISG	:	'Ishigaki - New Ishigaki Airport',
  KOJ	:	'Kagoshima',
  UKB	:	'Kobe',
  KCZ	:	'Kochi',
  KMQ	:	'Komatsu',
  KMJ	:	'Kumamoto',
  KUH	:	'Kushiro',
  UKY	:	'Kyoto',
  MMJ	:	'Matsumoto, Nagano',
  MYJ	:	'Matsuyama',
  MMY	:	'Miyako Jima (Ryuku Islands) - Hirara',
  KMI	:	'Miyazaki',
  HNA	:	'Morioka, Hanamaki',
  NGS	:	'Nagasaki',
  NGO	:	'Nagoya - Komaki AFB',
  KIJ	:	'Niigata',
  OIT	:	'Oita',
  OKJ	:	'Okayama',
  OKA	:	'Okinawa, Ryukyo Island - Naha',
  OSA	:	'Osaka, Metropolitan Area',
  ITM	:	'Osaka - Itami',
  KIX	:	'Osaka - Kansai International Airport',
  SDS	:	'Sado Shima',
  CTS	:	'Sapporo - New Chitose Airport',
  SDJ	:	'Sendai',
  TAK	:	'Takamatsu',
  TKS	:	'Tokushima',
  TYO	:	'Tokyo',
  HND	:	'Tokyo - Haneda',
  NRT	:	'Tokyo - Narita',
  TOY	:	'Toyama',
  UBJ	:	'Ube',
  GAJ	:	'Yamagata, Junmachi',
  YOK	:	'Yokohama',
  JGS	:	'Ji_an',
  CGQ	:	'Changchun',
  AMM	:	'Amman - Queen Alia International Airport',
  ADJ	:	'Amman - Amman-Marka International Airport',
  AQJ	:	'Aqaba',
  ALA	:	'Almaty (Alma Ata) - Almaty International Airport',
  TSE	:	'Astana - Astana International Airport',
  MYD	:	'Malindi',
  MBA	:	'Mombasa - Moi International',
  NBO	:	'Nairobi',
  KNS	:	'King Island',
  CXI	:	'Kiritimati (island) - Cassidy International Airport',
  ICN	:	'Incheon, Incheon International Airport',
  KWI	:	'Kuwait - Kuwait International',
  FRU	:	'Bishkek - Manas International Airport',
  VTE	:	'Vientiane - Wattay',
  RIX	:	'Riga',
  BEY	:	'Beirut - Beirut Rafic Hariri International Airport',
  MSU	:	'Maseru - Moshoeshoe International',
  DLC	:	'Dalian - Zhoushuizi International Airport',
  SHE	:	'Shenyang',
  MLW	:	'Monrovia - Metropolitan Area',
  ROB	:	'Monrovia - Roberts International',
  BEN	:	'Benghazi (Bengasi)',
  SEB	:	'Sehba',
  TIP	:	'Tripoli - Tripoli International',
  VNO	:	'Vilnius',

  LIF	:	'Lifou',
  LUX	:	'Luxembourg',
  MFM	:	'Macau - Macau International Airport',
  OHD	:	'Ohrid',
  SKP	:	'Skopje',
  TNR	:	'Antananarivo (Tanannarive) - Ivato International Airport',
  MJN	:	'Majunga',
  BLZ	:	'Blantyre (Mandala) - Chileka International Airport',
  LLW	:	'Lilongwe - Lilongwe International',
  BTU	:	'Bintulu',
  JHB	:	'Johor Bahru - Sultan Ismail International',
  BKI	:	'Kota Kinabalu',
  KUL	:	'Kuala Lumpur - International Airport',
  SZB	:	'Kuala Lumpur - Sultan Abdul Aziz Shah',
  KUA	:	'Kuantan',
  KCH	:	'Kuching',
  LBU	:	'Labuan',
  LGK	:	'Langkawi (islands)',
  MYY	:	'Miri',
  PEN	:	'Penang International',
  SBW	:	'Sibu',
  TWU	:	'Tawau',
  MLE	:	'Male - Velana International Airport',
  BKO	:	'Bamako - Bamako-Sénou International Airport',
  MLA	:	'Luga',
  UIT	:	'Jaluit Island',
  FDF	:	'Fort de France - Martinique Aimé Césaire International',
  NDB	:	'Nouadhibou',
  NKC	:	'Nouakchott',
  OUZ	:	'Zouerate',
  MRU	:	'Mauritius - S.Seewoosagur Ram International',
  RRG	:	'Rodrigues Island',
  DZA	:	'Dzaoudzi',
  ACA	:	'Acapulco',
  AGU	:	'Aguascaliente',
  CUN	:	'Cancun',
  CZA	:	'Chichen Itza',
  CUU	:	'Chihuahua - Gen Fierro Villalobos',
  CME	:	'Ciudad Del Carmen',
  CJS	:	'Ciudad Juarez',
  CEN	:	'Ciudad Obregon',
  CVM	:	'Ciudad Victoria',
  CLQ	:	'Colima',
  CZM	:	'Cozmel',
  CUL	:	'Culiacan',
  GDL	:	'Guadalajara',
  HMO	:	'Hermosillo - Gen. Pesqueira Garcia',
  HUX	:	'Huatulco',
  ZIH	:	'Ixtapa/Zihuatenejo',
  JAL	:	'Jalapa',
  LAP	:	'La Paz - Leon',
  LZC	:	'Lazaro Cardenas',
  BJX	:	'Leon',
  LTO	:	'Loreto',
  SJD	:	'Los Cabos',
  LMM	:	'Los Mochis',
  ZLO	:	'Manzanillo',
  MZT	:	'Mazatlan',
  MID	:	'Merida',
  MXL	:	'Mexicali',
  MEX	:	'Mexico City - Mexico City International Airport',
  AZP	:	'Mexico City - Atizapan',
  MEX	:	'Mexico City - Juarez International',
  NLU	:	'Mexico City - Santa Lucia',
  MTT	:	'Minatitlan',
  MTY	:	'Monterrey - Gen. Mariano Escobedo',
  NTR	:	'Monterrey - Aeropuerto Del Norte',
  MLM	:	'Morelia',
  NLD	:	'Nuevo Laredo',
  OAX	:	'Oaxaca - Xoxocotlan',
  PBC	:	'Puebla',
  PXM	:	'Puerto Escondido',
  PVR	:	'Puerto Vallarta',
  SJD	:	'San Jose Cabo',
  SLP	:	'San Luis Potosi',
  SRL	:	'Santa Rosalia',
  TAM	:	'Tampico - Gen. F. Javier Mina',
  TIJ	:	'Tijuana - Rodriguez',
  TGZ	:	'Tuxtla Gutierrez',
  UPN	:	'Uruapan',
  VER	:	'Veracruz',
  VSA	:	'Villahermosa',
  ZCL	:	'Zacatecas',
  PNI	:	'Pohnpei',
 
  ULN	:	'Ulaanbaatar - Buyant Uhaa Airport',
  TGD	:	'Podgorica',
  TIV	:	'Tivat',
  AGA	:	'Agadir',
  AHU	:	'Al Hoceima',
  CAS	:	'Casablanca',
  CMN	:	'Casablanca, Mohamed V',
  FEZ	:	'Fes',
  RAK	:	'Marrakesh - Menara Airport',
  OZZ	:	'Ouarzazate',
  OUD	:	'Oujda',
  RBA	:	'Rabat - Rabat-Salé Airport',
  TNG	:	'Tangier - Boukhalef',
  BEW	:	'Beira',
  MPM	:	'Maputo - Maputo International',
  MDL	:	'Mandalay - Mandalay-Annisaton Airport',
  RGN	:	'Rangoon (Yangon) - Mingaladon',
 
  MPA	:	'Katima Mulilo/Mpacha',
  KMP	:	'Keetmanshoop',
  LUD	:	'Luederitz',
  OKU	:	'Mokuti',
  OND	:	'Ondangwa',
  OMD	:	'Oranjemund',
  NDU	:	'Rundu',
  SWP	:	'Swakopmund',
  TSB	:	'Tsumeb',
  ERS	:	'Windhoek - Eros',
  WDH	:	'Windhoek - Hosea Kutako International',
  JKR	:	'Janakpur',
  JIR	:	'Jiri',
  JMO	:	'Jomsom',
  JUM	:	'Jumla',
  KTM	:	'Kathmandu - Tribhuvan International Airport',
  AMS	:	'Amsterdam - Amsterdam Airport Schiphol',
  HAG	:	'Den Haag (The Hague)',
  EIN	:	'Eindhoven',
  GRQ	:	'Groningen - Eelde',
  LEY	:	'Lelystad',
  MST	:	'Maastricht/Aachen',
  RTM	:	'Rotterdam',
  UDE	:	'Uden - Volkel Airport',
  BON	:	'Bonaire',
  CUR	:	'Curacao - Curaçao International Airport',
  SXM	:	'St. Marteen',
  ILP	:	'Ile des Pins',
  IOU	:	'Ile Ouen',
  MEE	:	'Mare',
  NOU	:	'Noumea',
  TOU	:	'Touho',
  AKL	:	'Auckland - Auckland International Airport',
  BHE	:	'Blenheim',
  CHC	:	'Christchurch',
  DUD	:	'Dunedin',
  HLZ	:	'Hamilton',
  IVC	:	'Incercargill',
  MFN	:	'Milford Sound',
  GTN	:	'Mount Cook',
  NSN	:	'Nelson',
  PMR	:	'Palmerston North',
  ZQN	:	'Queenstown',
  ROT	:	'Rotorua',
  TEU	:	'Te Anau',
  WLG	:	'Wellington',
  WHK	:	'Whakatane',
  WRE	:	'Whangarei',
  MGA	:	'Managua - Augusto C Sandino',
  AJY	:	'Agades',
  RLT	:	'Arlit',
  MFQ	:	'Maradi',
  NIM	:	'Niamey',
  ZND	:	'Zinder',
  ABV	:	'Abuja - Nnamdi Azikiwe International Airport',
  JOS	:	'Jos',
  KAN	:	'Kano',
  LOS	:	'Lagos - Murtala Muhammed Airport',
  PHC	:	'Port Harcourt',
  FNJ	:	'Pyongyang - Sunan International Airport',
  SPN	:	'Saipan',
  AES	:	'Alesund',
  ALF	:	'Alta',
  BDU	:	'Bardufoss',
  BGO	:	'Bergen',
  BOO	:	'Bodo',
  BNN	:	'Broennoeysund',
  EVE	:	'Evenes',
  FRO	:	'Floro',
  HFT	:	'Hammerfest',
  HAU	:	'Haugesund',
  KKN	:	'Kirkenes',
  KRS	:	'Kristiansand',
  KSU	:	'Kristiansund',
  LKL	:	'Lakselv',
  OSL	:	'Oslo - Oslo Airport, Gardermoen',
  FBU	:	'Oslo - Fornebu',
  TRF	:	'Oslo - Sandefjord',
  SOG	:	'Sogndal',
  SVG	:	'Stavanger',
  TOS	:	'Tromsoe',
  TRD	:	'Trondheim',
  MCT	:	'Muscat - Seeb',
  SLL	:	'Salalah',
  BHV	:	'Bahawalpur',
  BNP	:	'Bannu',
  CJL	:	'Chitral',
  DSK	:	'Dera Ismail Khan - Dera Ismail Khan Airport',
  LYP	:	'Faisalabad',
  GIL	:	'Gilgit',
  GWD	:	'Gwadar',
  HDD	:	'Hyderabad',
  ISB	:	'Islamabad - Benazir Bhutto International Airport',
  JAG	:	'Jacobabad',
  JIW	:	'Jiwani',
  KHI	:	'Karachi - Jinnah International Airport',
  KDD	:	'Khuzdar',
  OHT	:	'Kohat',
  LHE	:	'Lahore',
  MWD	:	'Mianwali',
  QML	:	'Mirpur',
  MJD	:	'Moenjodaro',
  MUX	:	'Multan',
  MFG	:	'Muzaffarabad',
  WNS	:	'Nawab Shah',
  PJG	:	'Panjgur',
  PSI	:	'Pasni',
  PEW	:	'Peshawar',
  UET	:	'Quetta',
  RYK	:	'Rahim Yar Khan - Shaikh Zayed International Airport',
  RAZ	:	'Rawala Kot',
  RWP	:	'Rawalpindi',
  SDT	:	'Saidu Sharif',
  MPD	:	'Sindhri',
  KDU	:	'Skardu',
  SUL	:	'Sui',
  SKZ	:	'Sukkur',
  TUK	:	'Turbat',
  PZH	:	'Zhob',
  GZA	:	'Gaza City - Gaza International Airport',
  JQE	:	'Jaque',
  PTY	:	'Panama City - Tocumen International',
  AYU	:	'Aiyura',
  AZB	:	'Amazon Bay',
  JAQ	:	'Jacquinot Bay',
  LAE	:	'Lae - Lae Nadzab Airport',
  MFO	:	'Manguna',
  POM	:	'Port Moresby - Jackson Field',
  ASU	:	'Asuncion - Asunción International Airport',
  IQT	:	'Iquitos',
  JAU	:	'Jauja',
  JJI	:	'Juanjui',
  JUL	:	'Juliaca',
  LIM	:	'Lima - J Chavez International',
  CEB	:	'Cebu City - Mactan-Cebu International',
  CYU	:	'Cuyo',
  JOL	:	'Jolo',
  NOP	:	'Mactan Island - Nab',
  MNL	:	'Manila - Ninoy Aquino International',
  GDN	:	'Gdansk',
  KRK	:	'Krakow (Cracow) - John Paul II International Airport',
  POZ	:	'Poznan, Lawica',
  SZZ	:	'Stettin',
  WAW	:	'Warsaw - Frédéric Chopin',
  FAO	:	'Faro',
  FNC	:	'Funchal',
  HOR	:	'Horta',
  LIS	:	'Lisbon - Lisboa',
  PDL	:	'Ponta Delgada',
  OPO	:	'Porto',
  PXO	:	'Porto Santo',
  SMA	:	'Santa Maria',
  TER	:	'Terceira',
  AAT	:	'Altay',
  CHG	:	'Chaoyang, Beijing - Chaoyang Airport',
  JMU	:	'Jiamusi - Jiamusi Airport',
  JGN	:	'Jiayuguan - Jiayuguan Airport',
  JIL	:	'Jilin',
  JDZ	:	'Jingdezhen',
  JHG	:	'Jinghong - Gasa Airport',
  JNG	:	'Jining',
  JJN	:	'Jinjiang',
  JNZ	:	'Jinzhou - Jinzhou Airport',
  JIU	:	'Jiujiang - Jiujiang Lushan Airport',
  HLH	:	'Ulanhot',
  BQN	:	'Aguadilla',
  MAZ	:	'Mayaguez',
  PSE	:	'Ponce',
  SJU	:	'San Juan - Luis Munoz Marin International Airport',
  DOH	:	'Doha - Doha International Airport',
  RUN	:	'Saint Denis - Roland Garros Airport',
  BUH	:	'Bucharest',
  OTP	:	'Bucharest - Henri Coandă International Airport',
  CND	:	'Constanta (Constanța) - Constanta Int_l Airport',
  AER	:	'Sochi',
  ARH	:	'Arkhangelsk',
  KHV	:	'Chabarovsk (Khabarovsk)',
  HTA	:	'Chita (Tschita)',
  IKT	:	'Irkutsk',
  KGD	:	'Kaliningrad',
  KZN	:	'Kazan - Kazan International Airport',
  MRV	:	'Mineralnye Vody',
  MOW	:	'Moscow - Metropolitan Area',
  DME	:	'Moscow - Domodedovo',
  SVO	:	'Moscow - Sheremetyevo',
  VKO	:	'Moscow - Vnukovo',
  MMK	:	'Murmansk',
  GOJ	:	'Nizhny Novgorod - Strigino International Airport',
  OVB	:	'Novosibirsk - Tolmachevo Airport',
  RVI	:	'Rostov-on-Don - Rostov-on-Don Airport',
  ROV	:	'Rostov-on-Don - Platov International Airport',
  KUF	:	'Samara - Kurumoch International Airport',
  SKX	:	'Saransk - Saransk Airport',
  LED	:	'St. Petersburg (Leningrad) - Pulkovo',
  UFA	:	'Ufa',
  UCT	:	'Ukhta',
  UUD	:	'Ulan-Ude',
  VLU	:	'Velikiye Luki (Welikije Luki)',
  YKS	:	'Yakutsk',
  SVX	:	'Yekaterinburg - Koltsovo Airport',
  KGL	:	'Kigali - Gregoire Kayibanda',
  SKB	:	'Basseterre - Robert L. Bradshaw International Airport',
  SLU	:	'Castries - George F. L. Charles Airport',
  UVF	:	'St. Lucia Hewanorra',
  SLU	:	'St. Lucia Vigle',
  CIW	:	'Canouan (island) - Canouan Airport',
  SVD	:	'Kingstown - E. T. Joshua Airport',
  SVD	:	'St. Vincent',
  UNI	:	'Union Island',
  APW	:	'Apia - Faleolo International Airport',
  TMS	:	'Sao Tome',
  DHA	:	'Dhahran',
  JED	:	'Jeddah - King Abdulaziz International',
  AJF	:	'Jouf',
  AHB	:	'Khamis Mushayat',
  MED	:	'Madinah (Medina) - Mohammad Bin Abdulaziz',
  MED	:	'Medina',
  RUH	:	'Riyadh - King Khaled International',
  TUU	:	'Tabuk',
  TIF	:	'Taif',
  YNB	:	'Yanbu',
  DMM	:	'Dammam, King Fahad International',
  EDI	:	'Edinburgh - Edinburgh Airport',
  DKR	:	'Dakar - Léopold Sédar Senghor International Airport',
  BEG	:	'Belgrad (Beograd) - Belgrade Nikola Tesla International',
  INI	:	'Nis',
  QND	:	'Novi Sad',
  PRN	:	'Pristina',
  SEZ	:	'Mahe - Seychelles International',
  XIY	:	'Xi_an - Xianyang',
  TNA	:	'Jinan',
  TAO	:	'Qingdao',
  TYN	:	'Taiyuan',
  CTU	:	'Chengdu - Shuangliu',
  CKG	:	'Chongqing - Jiangbei International Airport',
  FNA	:	'Freetown - Freetown-Lungi International Airport',
  SIN	:	'Singapore - Changi',
  QPG	:	'Singapore - Paya Lebar',
  XSP	:	'Singapore - Seletar',
  BTS	:	'Bratislava - M. R. Štefánik Airport',
  LJU	:	'Ljubljana - Brnik',
  MBX	:	'Maribor',
  GSI	:	'Guadalcanal',
  HIR	:	'Honiara Henderson International',
  MGQ	:	'Mogadishu',
  AGZ	:	'Aggeneys',
  ALJ	:	'Alexander Bay - Kortdoorn',
  ADY	:	'Alldays',
  BFN	:	'Bloemfontein - Bloemfontein Airport',
  CPT	:	'Cape Town - Cape Town International Airport',
  DUR	:	'Durban',
  ELS	:	'East London',
  ELL	:	'Ellisras',
  GRJ	:	'George',
  JNB	:	'Johannesburg - OR Tambo International Airport',
  KIM	:	'Kimberley',
  KLZ	:	'Kleinsee',
  HLA	:	'Lanseria',
  LUJ	:	'Lusisiki',
  MGH	:	'Margate',
  MEZ	:	'Messina',
  MBM	:	'Mkambati',
  MZY	:	'Mossel Bay',
  MZF	:	'Mzamba',
  NLP	:	'Nelspruit',
  MQP	:	'Nelspruit - Kruger Mpumalanga International Airport',
  NCS	:	'Newcastle',
  OUH	:	'Oudtshoorn',
  PHW	:	'Phalaborwa',
  PZB	:	'Pietermaritzburg',
  PTG	:	'Pietersburg',
  NTY	:	'Pilanesberg/Sun City',
  PBZ	:	'Plettenberg Bay',
  PLZ	:	'Port Elizabeth',
  PRY	:	'Pretoria - Wonderboom Apt.',
  RCB	:	'Richards Bay',
  SIS	:	'Sishen',
  SZK	:	'Skukuza',
  SBU	:	'Springbok',
  TCU	:	'Thaba_Nchu',
  ULD	:	'Ulundi',
  UTT	:	'Umtata',
  UTN	:	'Upington',
  VYD	:	'Vryheid',
  WVB	:	'Walvis Bay',
  WEL	:	'Welkom',
  PUS	:	'Pu San (Busan) - Gimhae International Airport',
  ICN	:	'Seoul - Incheon International Airport',
  SEL	:	'Seoul - Kimpo',
  USN	:	'Ulsan',
  JUB	:	'Juba',
  ALC	:	'Alicante',
  LEI	:	'Almeria',
  ACE	:	'Arrecife/Lanzarote',
  BJZ	:	'Badajoz',
  BCN	:	'Barcelona',
  BIO	:	'Bilbao',
  ODB	:	'Cordoba',
  FUE	:	'Fuerteventura',
  GRO	:	'Gerona',
  GRX	:	'Granada',
  XRY	:	'Jerez de la Frontera/Cadiz - La Parra',
  LCG	:	'La Coruna',
  LPA	:	'Las Palmas',
  MAD	:	'Madrid - Barajas Airport',
  MAH	:	'Mahon',
  AGP	:	'Malaga',
  MJV	:	'Murcia',
  OVD	:	'Oviedo',
  PMI	:	'Palma de Mallorca',
  REU	:	'Reus',
  EAS	:	'San Sebastian',
  SPC	:	'Santa Cruz de la Palma',
  SDR	:	'Santander',
  SCQ	:	'Santiago de Compostela',
  SVQ	:	'Sevilla',
  TCI	:	'Tenerife',
  TFS	:	'Tenerife - Sur Reina Sofia',
  TFN	:	'Tenerife - Norte Los Rodeos',
  VLC	:	'Valencia',
  VLL	:	'Valladolid',
  VDE	:	'Valverde',
  VGO	:	'Vigo',
  VIT	:	'Vitoria',
  ZAZ	:	'Zaragoza',
  CMB	:	'Colombo - Bandaranaike International Airport',
  JAF	:	'Jaffna - Kankesanturai',
  NEV	:	'Nevis',
  SKB	:	'St. Kitts',
  SFG	:	'St. Martin',
  KSL	:	'Kassala',
  KRT	:	'Khartoum - Khartoum International Airport',
  PBM	:	'Paramaribo - Zanderij International',
  LYR	:	'Longyearbyen - Svalbard',
  MTS	:	'Manzini - Matsapha International',
  GOT	:	'Gothenburg (Göteborg) - Landvetter',
  JHE	:	'Helsingborg',
  JKG	:	'Jönköping (Jonkoping) - Axamo Airport',
  KLR	:	'Kalmar',
  KSD	:	'Karlstad',
  KRN	:	'Kiruna',
  KID	:	'Kristianstad',
  LDK	:	'Lidkoeping',
  LLA	:	'Lulea',
  MMA	:	'Malmo (Malmoe)',
  MMX	:	'Malmo (Malmö) - Malmö Airport',
  NRK	:	'Norrkoeping',
  ORB	:	'Oerebro',
  RNB	:	'Ronneby',
  STO	:	'Stockholm Metropolitan Area',
  ARN	:	'Stockholm - Arlanda',
  BMA	:	'Stockholm - Bromma',
  SDL	:	'Sundsvall',
  UME	:	'Umea',
  VXO	:	'Vaexjoe',
  VST	:	'Vasteras',
  VBY	:	'Visby',
  ACH	:	'Altenrhein',
  BSL	:	'Basel',
  BRN	:	'Berne, Bern-Belp',
  ZDJ	:	'Berne, Railway Service',
  GVA	:	'Geneva - Geneva-Cointrin International Airport',
  LUG	:	'Lugano',
  ZRH	:	'Zurich - Kloten',
  EAP	:	'Basel/Mulhouse',
  ALP	:	'Aleppo',
  DAM	:	'Damascus, International',
  KHH	:	'Kaohsiung International',
  MZG	:	'Makung',
  TPE	:	'Taipei - Chiang Kai Shek',
  TAY	:	'Taipei - Sung Shan',
  DYU	:	'Dushanbe (Duschanbe) - Dushanbe Airport',
  ARK	:	'Arusha',
  DAR	:	'Dar es Salam (Daressalam) - Julius Nyerere Int_l',
  DOD	:	'Dodoma - Dodoma Airport',
  JRO	:	'Kilimadjaro',
  TFN	:	'Los Rodeos',
  TFS	:	'Reina Sofia',
  DMK	:	'Bangkok, Don Muang',
  BKK	:	'Bangkok, Suvarnabhumi International',
  CNX	:	'Chiang Mai - Chiang Mai International Airport',
  HDY	:	'Hatyai (Hat Yai)',
  NST	:	'Nakhon Si Thammarat',
  PYX	:	'Pattaya',
  HKT	:	'Phuket',
  UBP	:	'Ubon Ratchathani - Muang Ubon Airport',
  UTH	:	'Udon Thani',
  UTP	:	'Utapao (Pattaya)',
  NAS	:	'Bahamas - Lynden Pindling International Airport',
  DIL	:	'Dili - Nicolau Lobato International Airport',
  LFW	:	'Lome',
  TBU	:	'Nuku_alofa - Fua_Amotu International',
  POS	:	'Port of Spain - Piarco International',
  TAB	:	'Scarborough - Crown Point International',
  TAB	:	'Tobago',
  DJE	:	'Djerba',
  MIR	:	'Monastir',
  SFA	:	'Sfax',
  TUN	:	'Tunis - Carthage',
  ADA	:	'Adana',
  ADF	:	'Adiyaman',
  ANK	:	'Ankara',
  ESB	:	'Ankara - Esenboğa International Airport',
  AYT	:	'Antalya',
  BJV	:	'Bodrum - Milas Airport',
  DLM	:	'Dalaman',
  DNZ	:	'Denizli',
  ERC	:	'Erzincan',
  ERZ	:	'Erzurum',
  GZT	:	'Gaziantep',
  IST	:	'Istanbul - Istanbul Atatürk Airport',
  SAW	:	'Istanbul - Sabiha Gokcen',
  IZM	:	'Izmir',
  ADB	:	'Izmir - Adnan Menderes Airport',
  KCM	:	'Kahramanmaras',
  KYS	:	'Kars',
  ASR	:	'Kayseri',
  KYA	:	'Konya',
  MLX	:	'Malatya',
  KCM	:	'Maras',
  MQM	:	'Mardin',
  MSR	:	'Mus',
  SZF	:	'Samsun',
  VAS	:	'Sivas',
  TEQ	:	'Tekirdag - Corlu',
  TZX	:	'Trabzon',
  VAN	:	'Van - Ferit Melen',
  ASB	:	'Ashgabat - Saparmurat Turkmenbashy Int. Airport',
  EBB	:	'Entebbe - Entebbe International Airport',
  ULU	:	'Gulu',
  JIN	:	'Jinja',
  HRK	:	'Kharkov',
  KBP	:	'Kiev - Borispol',
  IEV	:	'Kiev - Zhulhany',
  LWO	:	'Lvov (Lwow, Lemberg)',
  NLV	:	'Nikolaev',
  ODS	:	'Odessa',
  SIP	:	'Simferopol',
  UDJ	:	'Uzhgorod',
  AUH	:	'Abu Dhabi - Abu Dhabi International',
  AAN	:	'Al Ain',
  FJR	:	'Alfujairah (Fujairah)',
  DXB	:	'Dubai - Dubai International Airport',
  FJR	:	'Fujairah, International Airport',
  RKT	:	'Ras al Khaymah (Ras al Khaimah)',
  SHJ	:	'Sharjah',
  ABZ	:	'Aberdeen',
  BRR	:	'Barra (the famous tidal beach landing)',
  BHD	:	'Belfast - George Best Belfast City Airport',
  BFS	:	'Belfast - Belfast International Airport',
  BEB	:	'Benbecula',
  BHX	:	'Birmingham - Birmingham International Airport',
  BLK	:	'Blackpool',
  BOH	:	'Bournemouth',
  BRS	:	'Bristol',
  CBG	:	'Cambrigde',
  CAL	:	'Campbeltown',
  CWL	:	'Cardiff - Cardiff Airport',
  CVT	:	'Coventry - Baginton',
  LDY	:	'Derry (Londonderry)',
  DSA	:	'Doncaster/Sheffield, Robin Hood International Airport',
  DND	:	'Dundee',
  EXT	:	'Exeter',
  FIE	:	'Fair Isle (Shetland)',
  FOU	:	'Foula (Shetland)',
  PIK	:	'Glasgow, Prestwick',
  GLA	:	'Glasgow',
  HUY	:	'Humberside',
  INV	:	'Inverness',
  ILY	:	'Islay',
  MSE	:	'Kent (Manston) Kent International',
  KOI	:	'Kirkwall (Orkney)',
  LEQ	:	'Land_s End',
  LBA	:	'Leeds/Bradford',
  LWK	:	'Lerwick/Tingwall (Shetland Islands)',
  LPL	:	'Liverpool',
  LON	:	'London Metropolitan Area',
  LCY	:	'London - City Airport',
  LGW	:	'London - Gatwick',
  LHR	:	'London - Heathrow',
  LTN	:	'London - Luton',
  STN	:	'London - Stansted',
  LDY	:	'Londonderry - Eglinton',
  LYX	:	'Lydd - Lydd International Airport',
  MAN	:	'Manchester',
  NQY	:	'Newquay',
  NCL	:	'Newcastle',
  NWI	:	'Norwich',
  EMA	:	'Nottingham - East Midlands',
  KOI	:	'Orkney - Kirkwall',
  OUK	:	'Out Skerries (Shetland)',
  SZD	:	'Sheffield, City Airport',
  DSA	:	'Sheffield, Doncaster, Robin Hood International Airport',
  SOU	:	'Southampton - Eastleigh',
  SEN	:	'Southend (London)',
  STN	:	'Stansted (London)',
  SYY	:	'Stornway',
  LSI	:	'Sumburgh (Shetland)',
  MME	:	'Teesside, Durham Tees Valley',
  UNT	:	'Unst (Shetland Island) - Baltasound Airport',
  WIC	:	'Wick',
  MVD	:	'Montevideo - Carrasco International Airport',
  MDY	:	'Midway Island - Sand Island Field',
  ABR	:	'Aberdeen (SD)',
  ABI	:	'Abilene (TX)',
  CAK	:	'Akron (OH)',
  ABY	:	'Albany (GA)',
  ALB	:	'Albany (NY) - Albany International Airport',
  ABQ	:	'Albuquerque (NM)',
  ABE	:	'Allentown (PA)',
  AOO	:	'Altoona (PA)',
  AXS	:	'Altus',
  AMA	:	'Amarillo (TX)',
  ANC	:	'Anchorage (AK) - Ted Stevens Anchorage International',
  ARB	:	'Ann Arbor (MI)',
  ANB	:	'Anniston (AL)',
  ATW	:	'Appelton/Neenah/Menasha (WI)',
  AVL	:	'Asheville (NC)',
  ASE	:	'Aspen, (CO) - Aspen-Pitkin County Airport',
  AHN	:	'Athens (GA)',
  ATO	:	'Athens (OH)',
  ATL	:	'Atlanta (GA) - Hartsfield Atlanta International Airport',
  ACY	:	'Atlantic City (NJ) - Atlantic City International',
  AGS	:	'Augusta (GA)',
  AUG	:	'Augusta (ME) - Augusta State Airport',
  AUS	:	'Austin (TX) - Austin-Bergstrom Airport',
  BFL	:	'Bakersfield (CA)',
  BWI	:	'Baltimore (MD) - Washington International Airport',
  BGR	:	'Bangor (ME)',
  BTR	:	'Baton Rouge (LA) - Baton Rouge Metropolitan Airport',
  BPT	:	'Beaumont/Pt. Arthur (TX)',
  BKW	:	'Beckley (WV)',
  BLI	:	'Bellingham (WA)',
  BJI	:	'Bemidji (MN)',
  BEH	:	'Benton Harbour (MI)',
  BET	:	'Bethel (AK)',
  BIL	:	'Billings (MT)',
  BHM	:	'Birmingham (AL)',
  BIS	:	'Bismarck (ND) - Bismarck Municipal Airport',
  BMI	:	'Bloomington (IL)',
  BMG	:	'Bloomington (IN)',
  BLF	:	'Bluefield (WV)',
  BOI	:	'Boise (ID) - Boise Air Terminal',
  BXS	:	'Borrego Springs (CA)',
  BOS	:	'Boston (MA) - General Edward Lawrence Logan',
  BZN	:	'Bozeman (MT)',
  BFD	:	'Bradford/Warren (PA) /Olean (NY)',
  BRD	:	'Brainerd (MN)',
  BDR	:	'Bridgeport (CT)',
  BKX	:	'Brookings (SD)',
  BQK	:	'Brunswick (GA)',
  BUF	:	'Buffalo/Niagara Falls (NY)',
  BHC	:	'Bullhead City (NV)',
  BUR	:	'Burbank (CA)',
  BRL	:	'Burlington IA',
  BTV	:	'Burlington (VT)',
  BTM	:	'Butte (MT)',
  CLD	:	'Carlsbad (CA)',
  CSN	:	'Carson City (NV)',
  CPR	:	'Casper (WY)',
  CDC	:	'Cedar City (UT)',
  CID	:	'Cedar Rapids IA',
  CMI	:	'Champaign (IL)',
  CHS	:	'Charleston (SC)',
  CRW	:	'Charleston (WV) - Yeager Airport',
  CLT	:	'Charlotte (NC)',
  CHO	:	'Charlottesville (VA)',
  CHA	:	'Chattanooga (TN)',
  CYS	:	'Cheyenne (WY) - Cheyenne Regional Airport',
  MDW	:	'Chicago (IL), Midway',
  ORD	:	'Chicago (IL), O_Hare International Airport',
  CHI	:	'Chicago (IL)',
  CIC	:	'Chico (CA)',
  CVG	:	'Cincinnati (OH) - Cincinnati/Northern Kentucky Int_l',
  CKB	:	'Clarksburg (WV)',
  BKL	:	'Cleveland (OH) , Burke Lakefront',
  CLE	:	'Cleveland (OH) - Cleveland Hopkins International',
  COD	:	'Cody/Powell/Yellowstone (WY)',
  KCC	:	'Coffmann Cove (AK)',
  CLL	:	'College Station/Bryan (TX)',
  COS	:	'Colorado Springs (CO)',
  CAE	:	'Columbia (SC) - Columbia Metropolitan Airport',
  CSG	:	'Columbus (GA)',
  CMH	:	'Columbus (OH) - Port Columbus International',
  CCR	:	'Concord (CA) - Buchanan Field',
  CON	:	'Concord (NH) - Concord Municipal Airport',
  CDV	:	'Cordova (AK)',
  CRP	:	'Corpus Christi (TX)',
  CGA	:	'Craig (AK)',
  CEC	:	'Crescent City (CA)',
  DAL	:	'Dallas (TX) , Love Field',
  DFW	:	'Dallas/Ft. Worth (TX) - Dallas/Fort Worth International',
  DAN	:	'Danville (VA)',
  DAY	:	'Dayton (OH)',
  DAB	:	'Daytona Beach (FL)',
  DEC	:	'Decatur (IL)',
  DEN	:	'Denver (CO) - Denver International Airport',
  DSM	:	'Des Moines (IA) - Des Moines International Airport',
  DET	:	'Detroit (MI) , Coleman A. Young Municipal',
  DTW	:	'Detroit (MI) , Wayne County Airport',
  DTT	:	'Detroit (MI) , Metropolitan Area',
  DVL	:	'Devils Lake (ND)',
  DLG	:	'Dillingham (AK)',
  DHN	:	'Dothan (AL)',
  DUJ	:	'Dubois (PA)',
  DBQ	:	'Dubuque IA',
  DLH	:	'Duluth (MN) /Superior (WI)',
  DRO	:	'Durango (CO)',
  DUT	:	'Dutch Harbor (AK)',
  EAU	:	'Eau Clarie (WI)',
  EKI	:	'Elkhart (IN)',
  EKO	:	'Elko (NV)',
  ELM	:	'Elmira (NY)',
  ELP	:	'El Paso (TX) - El Paso International Airport',
  ELY	:	'Ely (NV)',
  ERI	:	'Erie (PA)',
  ESC	:	'Escanaba (MI)',
  EUG	:	'Eugene (OR)',
  ACV	:	'Eureka (CA)',
  EVV	:	'Evansville (IN)',
  FAI	:	'Fairbanks (AK)',
  FAR	:	'Fargo (ND) (MN)',
  FMN	:	'Farmington (NM)',
  FYV	:	'Fayetteville (AR)',
  FAY	:	'Fayetteville/Ft. Bragg (NC)',
  FLG	:	'Flagstaff (AZ)',
  FNT	:	'Flint (MI)',
  FLO	:	'Florence (SC)',
  FOD	:	'Fort Dodge IA',
  FHU	:	'Fort Huachuca/Sierra Vista (AZ)',
  FLL	:	'Fort Lauderdale/Hollywood (FL)',
  FMY	:	'Fort Myers, Metropolitan Area (FL)',
  RSW	:	'Fort Myers, Southwest Florida Reg (FL)',
  FRI	:	'Fort Riley (KS) - Marshall AAF',
  FSM	:	'Fort Smith (AR)',
  VPS	:	'Fort Walton Beach (FL)',
  FWA	:	'Fort Wayne (IN)',
  DFW	:	'Fort Worth (TX) - Dallas/Fort Worth International Airport',
  FKL	:	'Franklin/Oil City (PA)',
  FAT	:	'Fresno (CA)',
  GAD	:	'Gadsden (AL)',
  GNV	:	'Gainesville (FL)',
  GCC	:	'Gilette (WY)',
  GGW	:	'Glasgow (MT)',
  GDV	:	'Glendive (MT)',
  GCN	:	'Grand Canyon (AZ)',
  GFK	:	'Grand Forks (ND)',
  GJT	:	'Grand Junction (CO)',
  GRR	:	'Grand Rapids (MI)',
  GPZ	:	'Grand Rapids (MN)',
  GTF	:	'Great Falls (MT)',
  GRB	:	'Green Bay (WI)',
  LWB	:	'Greenbrier/Lewisburg (WV)',
  GSO	:	'Greensboro/Winston Salem (NC)',
  GLH	:	'Greenville (MS)',
  PGV	:	'Greenville (NC)',
  GSP	:	'Greenville/Spartanburg (SC)',
  GON	:	'Groton/New London (CT)',
  GPT	:	'Gulfport/Biloxi (MS)',
  GUC	:	'Gunnison/Crested Butte (CO)',
  HNS	:	'Haines (AK)',
  CMX	:	'Hancock (MI)',
  HRL	:	'Harlingen/South Padre Island (TX)',
  HAR	:	'Harrisburg (PA) - Harrisburg Skyport',
  MDT	:	'Harrisburg (PA) - Harrisburg International',
  BDL	:	'Hartford (CT) /Springfield (MA)',
  HVR	:	'Havre (MT)',
  HLN	:	'Helena (MT)',
  HIB	:	'Hibbing (MN)',
  HKY	:	'Hickory (NC)',
  ITO	:	'Hilo (HI)',
  HHH	:	'Hilton Head Island (SC)',
  HOM	:	'Homer (AK)',
  HNL	:	'Honolulu (HI) - Honolulu International Airport',
  HNH	:	'Hoonah (AK)',
  HOU	:	'Houston (TX) , Hobby',
  IAH	:	'Houston, TX - George Bush Intercontinental Airport',
  HTS	:	'Huntington (WV)',
  HSV	:	'Huntsville (AL)',
  HON	:	'Huron (SD)',
  HYA	:	'Hyannis (MA)',
  HYG	:	'Hydaburg (AK)',
  IDA	:	'Idaho Falls (ID)',
  ILI	:	'Iliamna (AK)',
  IPL	:	'Imperial (CA)',
  IND	:	'Indianapolis (IN) International',
  INL	:	'International Falls (MN)',
  IYK	:	'Inykern (CA)',
  ITH	:	'Ithaca/Cortland (NY)',
  JAC	:	'Jackson Hole (WY)',
  JXN	:	'Jackson (MI) - Reynolds Municipal',
  MJQ	:	'Jackson,  MN',
  JAN	:	'Jackson (MS) - Jackson Internationall',
  HKS	:	'Jackson (MS) - Hawkins Field',
  MKL	:	'Jackson (TN) - Mckellar',
  JAC	:	'Jackson Hole (WY)',
  LRF	:	'Jacksonville (AR)  Little Rock AFB',
  NZC	:	'Jacksonville (FL) - Cecil Field NAS',
  NIP	:	'Jacksonville (FL) Jacksonville NAS',
  JAX	:	'Jacksonville (FL) - International',
  CRG	:	'Jacksonville (FL) - Craig Municipal',
  IJX	:	'Jacksonville (IL) - Municipal Airport',
  OAJ	:	'Jacksonville (NC)',
  JKV	:	'Jacksonville (TX)',
  JMS	:	'Jamestown (ND)',
  JHW	:	'Jamestown (NY)',
  JVL	:	'Janesville (WI) - Rock County',
  JEF	:	'Jefferson City (MO) - Jefferson Memorial',
  BGM	:	'Johnson City (NY) - Binghamton/Endicott/Johnson',
  JON	:	'Johnston Island',
  JST	:	'Johnstown (PA)',
  JBR	:	'Jonesboro (AR)  Jonesboro Airport',
  JLN	:	'Joplin (MO)',
  JNU	:	'Juneau (AK) - Juneau International Airport',
  OGG	:	'Kahului (HI)',
  AZO	:	'Kalamazoo/Battle Creek (MI)',
  FCA	:	'Kalispell (MT)',
  MUE	:	'Kamuela (HI)',
  MCI	:	'Kansas City (MO) - Kansas City International Airport',
  JHM	:	'Kapalua West (HI)',
  MKK	:	'Kaunakakai (HI)',
  ENA	:	'Kenai (AK)',
  KTN	:	'Ketchikan (AK)',
  EYW	:	'Key West (FL)',
  ILE	:	'Killeem (TX)',
  AKN	:	'King Salomon (AK)',
  ISO	:	'Kingston (NC)',
  LMT	:	'Klamath Fall (OR)',
  KLW	:	'Klawock (AK)',
  TYS	:	'Knoxville (TN)',
  ADQ	:	'Kodiak (AK)',
  KOA	:	'Kona (HI)',
  OTZ	:	'Kotzbue (AK)',
  WLB	:	'Labouchere Bay (AK)',
  LSE	:	'La Crosse (WI)',
  LAF	:	'Lafayette (IN)',
  LFT	:	'Lafayette, La',
  LCH	:	'Lake Charles (LA)',
  HII	:	'Lake Havasu City (AZ)',
  TVL	:	'Lake Tahoe (CA)',
  LNY	:	'Lanai City (HI)',
  LNS	:	'Lancaster (PA)',
  LAN	:	'Lansing (MI)',
  LAR	:	'Laramie (WY)',
  LRD	:	'Laredo (TX)',
  LAS	:	'Las Vegas (NV)',
  LBE	:	'Latrobe (PA)',
  PIB	:	'Laurel/Hattisburg (MS)',
  LAW	:	'Lawton (OK)',
  LEB	:	'Lebanon (NH)',
  LWS	:	'Lewiston (ID)',
  LWT	:	'Lewistown (MT)',
  LEX	:	'Lexington (KY)',
  LIH	:	'Lihue (HI)',
  LNK	:	'Lincoln (NE)',
  LIT	:	'Little Rock (AR)',
  LGB	:	'Long Beach (CA)',
  LIJ	:	'Long Island (AK)',
  ISP	:	'Long Island, Islip (NY) - Mac Arthur',
  GGG	:	'Longview/Kilgore (TX)',
  LAX	:	'Los Angeles (CA) - International',
  SDF	:	'Louisville (KY)',
  LBB	:	'Lubbock (TX)',
  LYH	:	'Lynchburg (VA)',
  LYO	:	'Lyons (KS) - Rice County Municipal',
  MCN	:	'Macon (GA)',
  MSN	:	'Madison (WI) - Dane County Regional Airport',
  MHT	:	'Manchester (NH)',
  MTH	:	'Marathon (FL)',
  MQT	:	'Marquette (MI)',
  MVY	:	'Martha_s Vineyard (MA)',
  MRB	:	'Martinsburg (WV)',
  MCW	:	'Mason City IA',
  MTO	:	'Mattoon (IL)',
  MFE	:	'McAllen (TX)',
  MFR	:	'Medford (OR)',
  MLB	:	'Melbourne (FL)',
  MEM	:	'Memphis (TN)',
  MCE	:	'Merced (CA)',
  MEI	:	'Meridian (MS)',
  MTM	:	'Metlakatla (AK)',
  MIA	:	'Miami (FL)',
  MAF	:	'Midland/Odessa (TX)',
  MLS	:	'Miles City (MT)',
  MKE	:	'Milwaukee (WI)',
  MSP	:	'Minneapolis - St. Paul International Airport (MN)',
  MOT	:	'Minot (ND)',
  MSO	:	'Missula (MT)',
  MHE	:	'Mitchell (SD)',
  MOB	:	'Mobile (AL) - Pascagoula (MS)',
  MOD	:	'Modesto (CA)',
  MLI	:	'Moline/Quad Cities (IL)',
  MLU	:	'Monroe (LA)',
  MRY	:	'Monterey (CA)',
  MGM	:	'Montgomery (AL) - Montgomery Regional Airport',
  MTJ	:	'Montrose/Tellruide (CO)',
  MGW	:	'Morgantown (WV)',
  MWH	:	'Moses Lake (WA)',
  MCL	:	'Mt. McKinley (AK)',
  MSL	:	'Muscle Shoals (AL)',
  MKG	:	'Muskegon (MI)',
  MYR	:	'Myrtle Beach (SC) - Myrtle Beach AFB',
  CRE	:	'Myrtle Beach (SC) - Grand Strand Airport',
  ACK	:	'Nantucket (MA)',
  APF	:	'Naples (FL)',
  BNA	:	'Nashville (TN)',
  EWN	:	'New Bern (NC)',
  HVN	:	'New Haven (CT)',
  MSY	:	'New Orleans, La',
  JFK	:	'New York - John F. Kennedy (NY)',
  LGA	:	'New York - LaGuardia (NY)',
  EWR	:	'New York - Newark (NJ)',
  NYC	:	'New York (NY)',
  SWF	:	'Newburgh (NY)',
  PHF	:	'Newport News/Williamsburg (VA)',
  IAG	:	'Niagara Falls International',
  OME	:	'Nome (AK)',
  ORF	:	'Norfolk/Virginia Beach (VA)',
  OTH	:	'North Bend (OR)',
  OAK	:	'Oakland (CA)',
  OKC	:	'Oklahoma City (OK) - Will Rogers World',
  OMA	:	'Omaha (NE)',
  ONT	:	'Ontario (CA)',
  SNA	:	'Orange County (Santa Ana) (CA)',
  ORL	:	'Orlando Metropolitan Area (FL)',
  MCO	:	'Orlando - International Airport (FL)',
  OSH	:	'Oshkosh (WI)',
  OWB	:	'Owensboro (KY)',
  OXR	:	'Oxnard (CA)',
  PAH	:	'Paducah (KY)',
  PGA	:	'Page/Lake Powell (AZ)',
  PKB	:	'Pakersburg (WV) /Marietta (OH)',
  PMD	:	'Palmdale/Lancaster (CA)',
  PSP	:	'Palm Springs (CA)',
  PFN	:	'Panama City (FL)',
  PSC	:	'Pasco (WA)',
  PLN	:	'Pellston (MI)',
  PDT	:	'Pendelton (OR)',
  PNS	:	'Pensacola (FL)',
  PIA	:	'Peoria/Bloomington (IL)',
  PSG	:	'Petersburg (AK)',
  PHL	:	'Philadelphia (PA) - International',
  PHX	:	'Phoenix (AZ) - Sky Harbor International',
  PIR	:	'Pierre (SD)',
  PIT	:	'Pittsburgh International Airport (PA)',
  PLB	:	'Plattsburgh (NY)',
  PIH	:	'Pocatello (ID)',
  CLM	:	'Port Angeles (WA)',
  PWM	:	'Portland (ME)',
  PDX	:	'Portland International (OR)',
  POU	:	'Poughkeepsie (NY)',
  PQI	:	'Presque Island (ME)',
  PVD	:	'Providence (RI)',
  SCC	:	'Prudhoe Bay (AK)',
  PUB	:	'Pueblo (CO)',
  PUW	:	'Pullman (WA)',
  UIN	:	'Quincy (IL)',
  RDU	:	'Raleigh/Durham (NC)',
  RAP	:	'Rapid City (SD)',
  RDG	:	'Reading (PA)',
  RDD	:	'Redding (CA)',
  RDM	:	'Redmond (OR)',
  RNO	:	'Reno (NV)',
  RHI	:	'Rhinelander (WI)',
  RIC	:	'Richmond (VA)',
  ROA	:	'Roanoke (VA)',
  RST	:	'Rochester (MN)',
  ROC	:	'Rochester (NY)',
  RKS	:	'Rock Springs (WY)',
  RFD	:	'Rockford (IL)',
  RKD	:	'Rockland (ME)',
  RWI	:	'Rocky Mount - Wilson (NC)',
  SMF	:	'Sacramento (CA)',
  MBS	:	'Saginaw/Bay City/Midland (MI)',
  SLE	:	'Salem (OR)',
  SNS	:	'Salinas (CA)',
  SBY	:	'Salisbury (MD)',
  SLC	:	'Salt Lake City (UT)',
  SJT	:	'San Angelo (TX)',
  SAT	:	'San Antonio (TX)',
  SAN	:	'San Diego - Lindberg Field International (CA)',
  SFO	:	'San Francisco - International Airport, SA',
  SJC	:	'San Jose (CA)',
  SBP	:	'San Luis Obisco (CA)',
  SNA	:	'Santa Ana - John Wayne Airport (CA)',
  SBA	:	'Santa Barbara (CA)',
  SMX	:	'Santa Maria (CA)',
  STS	:	'Santa Rosa (CA)',
  SRQ	:	'Sarasota/Bradenton (FL)',
  SAV	:	'Savannah (GA)',
  SCF	:	'Scottsdale (AZ)',
  SEA	:	'Seattle/Tacoma (WA)',
  SHD	:	'Shenandoah Valley/Stauton (VA)',
  SHR	:	'Sheridan (WY)',
  SHV	:	'Shreveport, La',
  SDY	:	'Sidney (MT)',
  SUX	:	'Sioux City IA',
  FSD	:	'Sioux Falls (SD)',
  SIT	:	'Sitka (AK)',
  SGY	:	'Skagway (AK)',
  SBN	:	'South Bend (IN)',
  GEG	:	'Spokane (WA)',
  SPI	:	'Springfield (IL)',
  SGF	:	'Springfield (MO)',
  SGU	:	'St. George (UT)',
  STL	:	'St. Louis (MO) Lambert–St. Louis International Airport',
  SCE	:	'State College/Belefonte (PA)',
  HDN	:	'Steamboat Springs (CO)',
  SCK	:	'Stockton (CA)',
  SUN	:	'Sun Valley (ID)',
  SYR	:	'Syracuse (NY)',
  TKA	:	'Talkeetna (AK)',
  TLH	:	'Tallahassee (FL)',
  TPA	:	'Tampa - International (FL)',
  TEX	:	'Telluride (CO)',
  HUF	:	'Terre Haute (IN)',
  TXK	:	'Texarkana (AR)',
  TVF	:	'Thief River Falls (MN)',
  KTB	:	'Thorne Bay (AK)',
  TOL	:	'Toledo (OH)',
  TVC	:	'Traverse City (MI)',
  TTN	:	'Trenton/Princeton (NJ)',
  TRI	:	'Tri-Cities Regional (TN) /VA',
  TUS	:	'Tucson (AZ)',
  TUP	:	'Tulepo (MS)',
  TUL	:	'Tulsa (OK)',
  TCL	:	'Tuscaloosa (AL)',
  TWF	:	'Twin Falls (ID)',
  TYR	:	'Tyler (TX)',
  UKI	:	'Ukiah (CA)',
  UNK	:	'Unalakleet (AK)',
  UPP	:	'Upolu Point (HI)',
  UCA	:	'Utica (NY) - Oneida County Airport',
  EGE	:	'Vail (CO)',
  VDZ	:	'Valdez (AK)',
  VLD	:	'Valdosta (GA)',
  VEL	:	'Vernal (UT)',
  VRB	:	'Vero Beach/Ft. Pierce (FL)',
  VIS	:	'Visalia (CA)',
  ACT	:	'Waco (TX)',
  ALW	:	'Walla Walla (WA)',
  BWI	:	'Washington DC - Baltimore Washington International',
  IAD	:	'Washington DC - Dulles International',
  DCA	:	'Washington DC - Ronald Reagan National',
  WAS	:	'Washington DC',
  ALO	:	'Waterloo IA',
  ATY	:	'Watertown (SD)',
  CWA	:	'Wausau/Stevens Point (WI)',
  EAT	:	'Wenatchee (WA)',
  PBI	:	'West Palm Beach (FL)',
  WYS	:	'West Yellowstone (MT)',
  HPN	:	'White Plains (NY)',
  SPS	:	'Wichita Falls (TX)',
  ICT	:	'Wichita (KS)',
  AVP	:	'Wilkes Barre/Scranton (PA)',
  IPT	:	'Williamsport (PA)',
  ISL	:	'Williston (ND)',
  ILM	:	'Wilmington (NC)',
  OLF	:	'Wolf Point (MT)',
  ORH	:	'Worcester (MA)',
  WRL	:	'Worland (WY)',
  WRG	:	'Wrangell (AK)',
  YKM	:	'Yakima (WA)',
  YAK	:	'Yakutat (AK)',
  YUM	:	'Yuma (AZ)',
  ESF	:	'Alexandria - Esler Field',
  SKD	:	'Samarkand - Samarkand International Airport',
  TAS	:	'Tashkent - International',
  TMZ	:	'Termez (Termes)',
  UGC	:	'Urgench',
  VLI	:	'Port Vila',
  SON	:	'Santo',
  ULB	:	'Ulei',
  BLA	:	'Barcelona',
  CCS	:	'Caracas - Simón Bolívar International Airport',
  CGU	:	'Ciudad Guayana',
  MAR	:	'Maracaibo - La Chinita International',
  PMV	:	'Margerita',
  PZO	:	'Puerto Ordaz',
  URM	:	'Uriman',
  VLN	:	'Valencia',
  SGN	:	'Ho Chi Minh City (Saigon) - Tan Son Nhat International',
  HUI	:	'Hue - Phu Bai',
  SGN	:	'Saigon (Ho Chi Minh City) - Tan Son Nhat International',
  HAN	:	'Hanoi - Noi Bai International Airport',
  EIS	:	'Beef Island - Terrance B. Lettsome',
  VIJ	:	'Virgin Gorda',
  STX	:	'St. Croix',
  STT	:	'St. Thomas',
  FUT	:	'Futuna',
  WLS	:	'Wallis',
  URC	:	'Urumqi',
  ADE	:	'Aden - Aden International Airport',
  SAH	:	'Sanaa (Sana_a) - Sana_a International',
  LUM	:	'Luxi - Mangshi',
  CIP	:	'Chipata',
  KIW	:	'Kitwe',
  LUN	:	'Lusaka - Lusaka International Airport',
  MFU	:	'Mfuwe',
  NLA	:	'N_Dola',
  HGH	:	'Hangchow (Hangzhou)',
  BFO	:	'Buffalo Range',
  BUQ	:	'Bulawayo',
  GWE	:	'Gweru',
  HRE	:	'Harare - Harare International Airport',
  HWN	:	'Hwange National Park',
  MVZ	:	'Masvingo',
  SAY	:	'Salisbury',
  ZIA : 'Moscow' ,
  IAS : 'Iasi',
  KIV : 'Chisinau'
}	;	

objStrApi.aircompany=
{
  'Международные авиалинии Украины' :'Ukraine International Airlines' ,
  'AR'  : 'Aerolineas Argentinas',
  'QS'  : 'Smartwings',
  'FR'  : 'Ryanair' ,
  '6H'  : 'Israir Airlines' ,
  'B6'  : 'JetBlue Airways' , 
  'PC'  : 'Pegasus Airlines' ,
  'U2'  : 'EasyJet' ,
  'VY'  : 'Vueling Airlines',
  'M3'	:	'ABSA Aerolinhas Brasileiras',
  'JP'	:	'Adria Airways',
  'A3'	:	'Aegean Airlines',
  'EI'	:	'Aer Lingus Cargo',
  'SU'	:	'Aeroflot',
  'AM'	:	'Aeromexico Cargo',
  'QO'	:	'Aeromexpress Cargo',
  'VV'	:	'Aerosvit',
  '6R'	:	'AeroUnion',
  'FK'	:	'Africa West',
  'AH'	:	'Air Algerie',
  'LM'	:	'Air ALM',
  'QN'	:	'Air Armenia',
  'KC'	:	'Air Astana',
  'BT'	:	'Air Baltic',
  'AC'	:	'Air Canada',
  'CA'	:	'Air China',
  'UX'	:	'Air Europa Cargo',
  'AF'	:	'Air France',
  
  'GL'	:	'Air Greenland',
  'LD'	:	'Air Hong Kong',
  'AI'	:	'Air India',
  'JM'	:	'Air Jamaica',
  'NX'	:	'Air Macau',
  'MD'	:	'Air Madagascar',
  'KM'	:	'Air Malta',
  'MK'	:	'Air Mauritius',
  '9U'	:	'Air Moldova',
  'NZ'	:	'Air New Zealand',
  'PX'	:	'Air Niugini',
  'HM'	:	'Air Seychelles',
  'RU'	:	'AirBridge Cargo',
  'AS'	:	'Alaska Airlines',
  'AZ'	:	'Alitalia',
  'AA'	:	'American Airlines',
  'M6'	:	'Amerijet International',
  'NH'	:	'ANA All Nippon Cargo',
  'JW'	:	'Arrow Air',
  'OZ'	:	'Asiana Airlines',
  'EV'	:	'Atlantic Southeast Airlines',
  '5Y'	:	'Atlas Air',
  'OS'	:	'Austrian Cargo',
  'SM'	:	'Avient',
  'J2'	:	'Azerbaijan Airlines',
  'BG'	:	'Biman Bangladesh',
  'BA'	:	'British Airways',
  'BD'	:	'British Midland Airways',
  'SN'	:	'Brussels Airlines',
  'FB'	:	'Bulgaria Air',
  'UZ'	:	'Buraq Air Transport (Arabic only)',
  '5C'	:	'CAL Cargo Air Lines',
  'UY'	:	'Cameroon Airlines',
  'CP'	:	'Canadian Airlines Int´l',
  '2G'	:	'CargoItalia (alternate)',
  'CV'	:	'Cargolux Airlines',
  'C8'	:	'Cargolux Italia',
  'BW'	:	'Caribbean Airlines',
  'CX'	:	'Cathay Pacific Airways',
  'KX'	:	'Cayman Airways',
  'WE'	:	'Centurion Air Cargo',
  'CI'	:	'China Airlines',
  'CK'	:	'China Cargo Airlines',
  'MU'	:	'China Eastern Airlines',
  'CZ'	:	'China Southern Airlines',
  'A2'	:	'Cielos Airlines',
  'OH'	:	'Comair',
  'DE'	:	'Condor Flugdienst',
  'CO'	:	'Continental Airlines',
  'CM'	:	'Copa Airlines Cargo',
  '7C'	:	'Coyne Airways',
  'OU'	:	'Croatia Airlines',
  'CY'	:	'Cyprus Airways',
  'OK'	:	'Czech Airlines',
  'DL'	:	'Delta Air Lines',
  'QY'	:	'DHL Aviation / European Air Transport',
  'ER'	:	'DHL Aviation/DHL Airways',
  'KA'	:	'Dragonair',
  'MS'	:	'Egyptair',
  'LY'	:	'EL AL',
  'EK'	:	'Emirates',
  'OV'	:	'Estonian Air',
  'ET'	:	'Ethiopian Airlines',
  'EY'	:	'ETIHAD Airways',
  'BR'	:	'Eva Airways',
  'EF'	:	'Far Eastern Air Transport',
  'FX'	:	'Fedex',
  'AY'	:	'Finnair',
  'RF'	:	'Florida West International Airways',
  'GA'	:	'Garuda Indonesia',
  '5S'	:	'Global Aviation and Services',
  'GD'	:	'Grandstar Cargo',
  'IJ'	:	'Great Wall Airlines',
  'GF'	:	'Gulf Air',
  'HU'	:	'Hainan Airlines (Chinese)',
  'MH'	:	'Homepage',
  'N8'	:	'Hong Kong Airlines',
  'IB'	:	'Iberia',
  'FI'	:	'Icelandair',
  'IC'	:	'Indian Airlines',
  '7I'	:	'Insel Air Cargo',
  'IR'	:	'Iran Air',
  'JI'	:	'Jade Cargo International',
  'JD'	:	'Japan Air System',
  'JL'	:	'Japan Airlines',
  'JU'	:	'JAT Airways',
  '9W'	:	'Jet Airways',
  'K4'	:	'Kalitta Air',
  'KD'	:	'KD Avia',
  'KQ'	:	'Kenya Airways',
  'IT'	:	'Kingfisher Airlines',
  'KL'	:	'KLM Cargo',
  'KE'	:	'Korean Air',
  'KU'	:	'Kuwait Airways',
  'LR'	:	'LACSA Airlines of Costa Rica',
  'LA'	:	'LAN Chile',
  'NG'	:	'Lauda Air',
  'LI'	:	'LIAT Airlines',
  'LN'	:	'Libyan Airlines',
  'LO'	:	'LOT Polish Airlines',
  'LT'	:	'LTU (Leisure Cargo)',
  'LH'	:	'Lufthansa Cargo AG',
  'MH'	:	'Malaysian Airline System',
  'MA'	:	'Malev Hungarian Airlines',
  'AE'	:	'Mandarin Airlines',
  'M2'	:	'Mario’s Air',
  'MP'	:	'Martinair Cargo',
  'MY'	:	'MASAir',
  'ME'	:	'Middle East Airlines',
  'MB'	:	'MNG Airlines',
  'UL'	:	'more AWB tracking',
  'N8'	:	'National Air Cargo',
  'KZ'	:	'Nippon Cargo Airlines',
  'NC'	:	'Northern Air Cargo',
  'NW'	:	'Northwest Airlines (alternate site)',
  'OA'	:	'Olympic Airways',
  'PK'	:	'Pakistan Int´l Airlines',
  'PR'	:	'Philippine Airlines',
  'PO'	:	'Polar Air Cargo',
  'QF'	:	'Qantas Airways',
  'QR'	:	'Qatar Airways',
  'AT'	:	'Royal Air Maroc',
  'BI'	:	'Royal Brunei Airlines',
  'RJ'	:	'Royal Jordanian',
  'S6'	:	'SAC South American Airways',
  'SK'	:	'SAS-Scandinavian Airlines System',
  'SP'	:	'SATA Air Acores',
  'SV'	:	'Saudi Arabian Airlines',
  'SC'	:	'Shandong Airlines (Chinese)',
  'FM'	:	'Shanghai Airlines',
  'F4'	:	'Shanghai Airlines Cargo',
  'ZH'	:	'Shenzhen Airlines (Chinese)',
  'S7'	:	'Siberia Airlines',
  '3U'	:	'Sichuan Airlines',
  'SQ'	:	'Singapore Airlines',
  'OO'	:	'Sky West Airlines',
  'SA'	:	'South African Airways',
  'WN'	:	'Southwest Airlines',
  'UL'	:	'SriLankan Cargo',
  'XQ'	:	'Sun Express',
  'LX'	:	'Swiss',
  'RB'	:	'Syrian Arab Airlines',
  'DT'	:	'TAAG Angola Airlines',
  'B1'	:	'TAB Cargo',
  'TA'	:	'TACA',
  'JJ'	:	'TAM Brazilian Airlines',
  'QT'	:	'Tampa Airlines',
  'TP'	:	'TAP Air Portugal',
  'TG'	:	'Thai Airways',
  '3V'	:	'TNT Airways',
  'TL'	:	'Trans Mediterranean Airways',
  'TK'	:	'Turkish Airlines',
  'PS'	:	'Ukraine Int´l Airlines',
  'UA'	:	'United Airlines Cargo',
  '5X'	:	'UPS Air Cargo',
  'US'	:	'USAirways',
  'RG'	:	'VARIG Brazilian Airlines',
  'RG'	:	'VARIG Brazilian Airlines',
  'VN'	:	'Vietnam Airlines',
  'VS'	:	'Virgin Atlantic',
  'MF'	:	'Xiamen Airlines',
  'Y8'	:	'Yangtze River Express Airlines',
  'IY'	:	'Yemenia Yemen Airways'
}

objStrApi.aircraft={
A124	:	'Antonov AN-124 Ruslan',
A140	:	'Antonov AN-140',
A148	:	'Antonov An-148',
A158	:	'Antonov An-158',
A19N	:	'Airbus A319neo',
A20N	:	'Airbus A320neo',
A21N	:	'Airbus A321neo',
A21NX	:	'Airbus A321LR',
A21NY	:	'Airbus A321XLR',
A210	:	'Aquila A 210',
A225	:	'Antonov An-225 Mriya',
A306	:	'Airbus A300-600',
A30B	:	'Airbus A300B2, A300B4, and A300C4',
A310	:	'Airbus A310-200',
A310	:	'Airbus A310-300',
A318	:	'Airbus A318',
A318	:	'Airbus A318 (sharklets)',
A319	:	'Airbus A319',
A319	:	'Airbus A319 (sharklets)',
A320	:	'Airbus A320',
A320	:	'Airbus A320 (sharklets)',
A20F	:	'Airbus A320 (P2F conversion)',
A321	:	'Airbus A321',
A321	:	'Airbus A321 (sharklets)',
A21F	:	'Airbus A321 (P2F conversion)',
A332	:	'Airbus A330-200',
A333	:	'Airbus A330-300',
A332	:	'Airbus A330-200 Freighter',
A333	:	'Airbus A330-300 Freighter',
A337	:	'Airbus A330-700 "Beluga XL"',
A338	:	'Airbus A330-800',
A339	:	'Airbus A330-900',
A342	:	'Airbus A340-200',
A343	:	'Airbus A340-300',
A345	:	'Airbus A340-500',
A346	:	'Airbus A340-600',
A359	:	'Airbus A350-900',
A35K	:	'Airbus A350-1000',
A388	:	'Airbus A380-800',
A3ST	:	'Airbus A300-600ST "Super Transporter" / "Beluga"',
A400	:	'Airbus A400M Atlas',
A5	:	'ICON A5',
A748	:	'Hawker Siddeley HS 748',
AC68	:	'Gulfstream/Rockwell (Aero) Commander',
AC90	:	'Gulfstream/Rockwell (Aero) Turbo Commander',
AJ27	:	'COMAC ARJ21',
AN12	:	'Antonov AN-12',
AN2	:	'Antonov An-2',
AN24	:	'Antonov AN-24',
AN26	:	'Antonov AN-26',
AN28	:	'Antonov AN-28',
AN30	:	'Antonov AN-30',
AN32	:	'Antonov AN-32',
AN72	:	'Antonov AN-72 / AN-74',
AP22	:	'Aeroprakt A-22 Foxbat / A-22 Valor / A-22 Vision',
AS32	:	'Eurocopter AS332 Super Puma',
AS50	:	'Eurocopter AS350 Écureuil / AS355 Ecureuil 2 / AS550 Fennec',
AT43	:	'Aerospatiale/Alenia ATR 42-300 / 320',
AT45	:	'Aerospatiale/Alenia ATR 42-500',
AT46	:	'Aerospatiale/Alenia ATR 42-600',
AT72	:	'Aerospatiale/Alenia ATR 72',
AT73	:	'Aerospatiale/Alenia ATR 72-200 series',
AT75	:	'Aerospatiale/Alenia ATR 72-500',
AT76	:	'Aerospatiale/Alenia ATR 72-600',
ATL	:	'Robin ATL',
ATP	:	'British Aerospace ATP',
B06	:	'Bell 206 JetRanger',
B06T	:	'Bell 206 TwinRanger',
B105	:	'Eurocopter (MBB) Bo.105',
B190	:	'Beechcraft 1900',
B212	:	'Bell 212',
B37M	:	'Boeing 737 MAX 7',
B38M	:	'Boeing 737 MAX 8',
B39M	:	'Boeing 737 MAX 9',
B3XM	:	'Boeing 737 MAX 10',
B412	:	'Bell 412',
B429	:	'Bell 429',
B461	:	'BAe 146-100',
B462	:	'BAe 146-200',
B463	:	'BAe 146-300',
B703	:	'Boeing 707',
B712	:	'Boeing 717',
B720	:	'Boeing 720B',
B721	:	'Boeing 727-100',
B722	:	'Boeing 727-200',
B732	:	'Boeing 737-200',
B733	:	'Boeing 737-300',
B734	:	'Boeing 737-400',
B735	:	'Boeing 737-500',
B736	:	'Boeing 737-600',
B738	:	'Boeing 737-800',
B739	:	'Boeing 737-900 / Boeing 737-900ER',
B733	:	'Boeing 737-300 Winglets',
B735	:	'Boeing 737-500 Winglets',
B732	:	'Boeing 737-200 Freighter',
B737	:	'Boeing 737-700 / Boeing 737-700ER',
B738	:	'Boeing 737-800 Winglets',
B739	:	'Boeing 737-900 Winglets',
B738	:	'Boeing 737-800 Freighter Winglets',
B734	:	'Boeing 737-400 Freighter',
B738	:	'Boeing 737-800 Freighter',
B737	:	'Boeing 737-700 Winglets',
B733	:	'Boeing 737-300 Freighter',
B741	:	'Boeing 747-100',
B741	:	'Boeing 747-100 Freighter',
B742	:	'Boeing 747-200',
B742	:	'Boeing 747-200M',
B742	:	'Boeing 747-200F',
B743	:	'Boeing 747-300',
B743	:	'Boeing 747-300M',
B744	:	'Boeing 747-400 / Boeing 747-400ER',
B744	:	'Boeing 747-400M',
B744	:	'Boeing 747-400F / Boeing 747-400ERF',
B748	:	'Boeing 747-8I',
B748	:	'Boeing 747-8F',
B74D	:	'Boeing 747-400D (deprecated 2018: no longer flying)',
B74R	:	'Boeing 747SR',
B74R	:	'Boeing 747SR Freighter',
B74S	:	'Boeing 747SP',
B752	:	'Boeing 757-200',
B752	:	'Boeing 757F',
B753	:	'Boeing 757-300',
B762	:	'Boeing 767-200 / Boeing 767-200ER',
B763	:	'Boeing 767-300',
B764	:	'Boeing 767-400ER',
B763	:	'Boeing 767-300 Winglets / Boeing 767-300ER',
B762	:	'Boeing 767-200 Freighter / Boeing 767-200ER',
B763	:	'Boeing 767-300 Freighter',
B772	:	'Boeing 777-200 / Boeing 777-200ER',
B773	:	'Boeing 777-300',
B778	:	'Boeing 777-8',
B779	:	'Boeing 777-9',
B77L	:	'Boeing 777-200 Freighter',
B77L	:	'Boeing 777-200LR',
B77W	:	'Boeing 777-300ER',
B788	:	'Boeing 787-8',
B789	:	'Boeing 787-9',
B78X	:	'Boeing 787-10',
BA11	:	'British Aerospace (BAC) One Eleven',
BCS1	:	'Airbus A220-100',
BCS3	:	'Airbus A220-300',
BE40	:	'Hawker 400',
BE55	:	'Beechcraft Baron / 55 Baron',
BE58	:	'Beechcraft Baron / 58 Baron',
BE99	:	'Beechcraft Model 99',
BELF	:	'Shorts SC-5 Belfast',
BER2	:	'Beriev Be-200 Altair',
BL8	:	'8KCAB Decathlon, 8GCBC Scout',
BLCF	:	'Boeing 747 LCF Dreamlifter',
BN2P	:	'Pilatus Britten-Norman BN-2A/B Islander',
C130	:	'Lockheed L-182 / 282 / 382 (L-100) Hercules',
C140	:	'Cessna 140',
C152	:	'Cessna 152',
C162	:	'Cessna 162',
C172	:	'Cessna 172',
C177	:	'Cessna 177 Cardinal',
C182	:	'Cessna 182 Skylane',
C82R	:	'Cessna R182 Skylane RG',
C206	:	'Cessna 206 Stationair',
C208	:	'Cessna 208 Caravan',
C210	:	'Cessna 210 Centurion',
T210	:	'Cessna 210 Centurion Turbo',
C212	:	'CASA / IPTN 212 Aviocar',
C25A	:	'Cessna Citation CJ2',
C25B	:	'Cessna Citation CJ3',
C25C	:	'Cessna Citation CJ4',
C30J	:	'Lockheed Martin C-130J Hercules',
C310	:	'Cessna 310',
C46	:	'Curtiss C-46 Commando',
C500	:	'Cessna Citation I',
C510	:	'Cessna Citation Mustang',
C525	:	'Cessna CitationJet',
C550	:	'Cessna Citation II',
C560	:	'Cessna Citation V',
C56X	:	'Cessna Citation Excel',
C650	:	'Cessna Citation III, VI, VII',
C680	:	'Cessna Citation Sovereign',
C72R	:	'Cessna 172 Cutlass RG',
C750	:	'Cessna Citation X',
C77R	:	'Cessna 177 Cardinal RG',
C919	:	'COMAC C919',
CH7A	:	'7AC Champ, 7ECA Citabria',
CH7B	:	'7GCAA, 7GCBC, 7KCAB Citabria',
CL2T	:	'Bombardier 415',
CL30	:	'Bombardier BD-100 Challenger 300',
CL60	:	'Canadair Challenger',
CN35	:	'CASA/IPTN CN-235',
CONC	:	'Concorde (deprecated: no longer flying)',
CONI	:	'Lockheed L-1049 Super Constellation',
CRJ1	:	'Canadair Regional Jet 100',
CRJ2	:	'Canadair Regional Jet 200',
CRJ7	:	'Canadair Regional Jet 700 | Regional Jet 550',
CRJ9	:	'Canadair Regional Jet 900',
CRJX	:	'Canadair Regional Jet 1000',
CVLP	:	'Convair CV-240 & -440',
CVLT	:	'Convair CV-580, Convair CV-600, Convair CV-640',
D228	:	'Dornier 228',
D328	:	'Fairchild Dornier Do.328',
DA40	:	'Diamond DA40',
DA42	:	'Diamond DA42',
DA62	:	'Diamond DA62',
DC10	:	'Douglas DC-10-10 / -15 Passenger',
DC10	:	'Douglas DC-10-30 / -40 Passenger',
DC10	:	'Douglas DC-10-30 Combi',
DC10	:	'Douglas DC-10-10 Freighter',
DC10	:	'Douglas DC-10-30 / -40 Freighter',
DC3	:	'Douglas DC-3',
DC6	:	'Douglas DC-6',
DC85	:	'Douglas DC-8-50',
DC86	:	'Douglas DC-8-62',
DC87	:	'Douglas DC-8-72',
DC91	:	'Douglas DC-9-10',
DC92	:	'Douglas DC-9-20',
DC93	:	'Douglas DC-9-30',
DC94	:	'Douglas DC-9-40',
DC95	:	'Douglas DC-9-50',
DH2T	:	'De Havilland Canada DHC-2 Turbo-Beaver',
DH62	:	'De Havilland Comet 2 (deprecated code)',
DH64	:	'De Havilland Comet 4 (deprecated code)',
DH8A	:	'De Havilland Canada DHC-8-100 Dash 8 / 8Q',
DH8B	:	'De Havilland Canada DHC-8-200 Dash 8 / 8Q',
DH8C	:	'De Havilland Canada DHC-8-300 Dash 8 / 8Q',
DH8D	:	'De Havilland Canada DHC-8-400 Dash 8Q',
DHC2	:	'De Havilland Canada DHC-2 Beaver',
DHC3	:	'De Havilland Canada DHC-3 Otter',
DHC4	:	'De Havilland Canada DHC-4 Caribou',
DHC5	:	'De Havilland Canada DHC-5 Buffalo',
DHC6	:	'De Havilland Canada DHC-6 Twin Otter',
DHC7	:	'De Havilland Canada DHC-7 Dash 7',
DOVE	:	'De Havilland DH.104 Dove',
E110	:	'Embraer EMB 110 Bandeirante',
E120	:	'Embraer EMB 120 Brasilia',
E135	:	'Embraer RJ135',
E135	:	'Embraer RJ140',
E145	:	'Embraer RJ145',
E170	:	'Embraer 170',
E190	:	'Embraer 190 / Lineage 1000',
E195	:	'Embraer 195',
E290	:	'Embraer E190-E2',
E295	:	'Embraer E195-E2',
E35L	:	'Embraer Legacy 600 / Legacy 650',
E50P	:	'Embraer Phenom 100',
E545	:	'Embraer Legacy 450 / Praetor 500',
E550	:	'Embraer Legacy 500 / Praetor 600',
E55P	:	'Embraer Phenom 300',
E75L	:	'Embraer 175 (long wing)',
E75S	:	'Embraer 175 (short wing)',
EA30	:	'Airbus A300 (deprecated 1997: code replaced)',
EA31	:	'Airbus A310 (deprecated 1997: code replaced)',
EA32	:	'Airbus A320 (deprecated 1997: code replaced)',
EA33	:	'Airbus A330 (deprecated 1997: code replaced)',
EA34	:	'Airbus A340 (deprecated 1997: code replaced)',
EA50	:	'Eclipse 500',
EC20	:	'Eurocopter EC120 Colibri / Harbin HC120',
EC25	:	'Eurocopter EC225 Super Puma',
EC30	:	'Eurocopter EC130',
EC35	:	'Eurocopter EC135 / EC635',
EC45	:	'Eurocopter EC145',
EC55	:	'Eurocopter EC155',
EC75	:	'Eurocopter EC175',
ECHO	:	'Tecnam P92 Echo / P92 Eaglet / P92 SeaSky',
EV97	:	'EV-97 EuroStar / EV-97 Harmony',
EVSS	:	'Evektor SportStar',
EXPL	:	'MD Helicopters MD900 Explorer',
F100	:	'Fokker 100',
F27	:	'Fokker F27 Friendship',
F28	:	'Fokker F28 Fellowship',
F2TH	:	'Dassault Falcon 2000',
F406	:	'Reims-Cessna F406 Caravan II',
F50	:	'Fokker 50',
F70	:	'Fokker 70',
F900	:	'Dassault Falcon 900',
FA24	:	'Fairchild 24',
FA50	:	'Dassault Falcon 50',
FA7X	:	'Dassault Falcon 7X',
G159	:	'Gulfstream Aerospace G-159 Gulfstream I',
G21	:	'Grumman G-21 Goose',
G280	:	'Gulfstream G280',
G73T	:	'Grumman G-73 Turbo Mallard',
GA8	:	'GippsAero GA8 Airvan',
GL5T	:	'Bombardier BD-700 Global 5000',
GLEX	:	'Bombardier Global Express / Raytheon Sentinel',
GLF4	:	'Gulfstream IV',
GLF5	:	'Gulfstream V',
GLF6	:	'Gulfstream G650',
GOLF	:	'Tecnam P96',
H25B	:	'British Aerospace 125 series / Hawker/Raytheon 700/800/800XP/850/900',
H25C	:	'British Aerospace 125-1000 series / Hawker/Raytheon 1000',
HDJT	:	'Honda HA-420',
HERN	:	'De Havilland DH.114 Heron',
I114	:	'Ilyushin IL114',
IL18	:	'Ilyushin IL18',
IL62	:	'Ilyushin IL62',
IL76	:	'Ilyushin IL76',
IL86	:	'Ilyushin IL86',
IL96	:	'Ilyushin IL96',
J328	:	'Fairchild Dornier 328JET',
JS31	:	'British Aerospace Jetstream 31',
JS32	:	'British Aerospace Jetstream 32',
JS41	:	'British Aerospace Jetstream 41',
JU52	:	'Junkers Ju 52/3M',
K35R	:	'Boeing KC-135 Stratotanker',
L101	:	'Lockheed L-1011 Tristar',
L188	:	'Lockheed L-188 Electra',
L410	:	'LET 410',
LJ35	:	'Learjet 35 / 36 / C-21A',
LJ60	:	'Learjet 60',
MD11	:	'McDonnell Douglas MD-11',
MD11	:	'McDonnell Douglas MD-11F',
MD11	:	'McDonnell Douglas MD-11C',
MD81	:	'McDonnell Douglas MD-81',
MD82	:	'McDonnell Douglas MD-82',
MD83	:	'McDonnell Douglas MD-83',
MD87	:	'McDonnell Douglas MD-87',
MD88	:	'McDonnell Douglas MD-88',
MD90	:	'McDonnell Douglas MD-90',
MI24	:	'Mil Mi-24 / Mi-25 / Mi-35',
MI8	:	'MIL Mi-8 / Mi-17 / Mi-171 / Mil-172',
MU2	:	'Mitsubishi Mu-2',
N262	:	'Aerospatiale (Nord) 262',
NOMA	:	'Government Aircraft Factories N22B / N24A Nomad',
P06T	:	'Tecnam P2006T',
P8	:	'Boeing P-8 Poseidon',
P180	:	'Piaggio P.180 Avanti',
P208	:	'Tecnam P2008',
P212	:	'Tecnam P2012 Traveller',
P28A	:	'Piper PA-28 (up to 180 hp)',
P28B	:	'Piper PA-28 (above 200 hp)',
P68	:	'Partenavia P.68',
PA31	:	'Piper PA-31 Navajo',
PA44	:	'Piper PA-44 Seminole',
PA46	:	'Piper PA-46',
PC12	:	'Pilatus PC-12',
PC6T	:	'Pilatus PC-6 Turbo Porter',
PC24	:	'Pilatus PC-24',
PIPA	:	'Pipistrel Panthera',
PISI	:	'Pipistrel Sinus[4]',
PITA	:	'Pipistrel Taurus[4]',
PIVI	:	'Pipistrel Virus[4]',
R200	:	'Robin HR200/R2000 series, Alpha160A',
RJ1H	:	'Avro RJ100',
RJ70	:	'Avro RJ70',
RJ85	:	'Avro RJ85',
RV4	  :	'Aircraft RV-4',
S210	:	'Aerospatiale (Sud Aviation) Se.210 Caravelle (deprecated: no longer flying)',
S58T	:	'Sikorsky S-58T',
S601	:	'Aerospatiale SN.601 Corvette',
S61	:	'Sikorsky S-61',
S65C	:	'Eurocopter (Aerospatiale) SA365C / SA365N Dauphin 2',
S76	:	'Sikorsky S-76',
S92	:	'Sikorsky S-92',
SB20	:	'Saab 2000',
SC7	:	'Shorts SC-7 Skyvan',
SF34	:	'Saab SF340A/B',
SF50	:	'Cirrus SF50 Vision Jet',
SH33	:	'Shorts SD.330',
SH36	:	'Shorts SD.360',
SIRA	:	'Tecnam P2002 Sierra',
SPIT	:	'Supermarine Spitfire',
SR22	:	'Cirrus SR22',
SU95	:	'Sukhoi Superjet 100-95',
SW4	:	'Fairchild Swearingen Metroliner',
T134	:	'Tupolev Tu-134',
T144	:	'Tupolev Tu-144 (deprecated code: no longer flying)',
T154	:	'Tupolev Tu-154',
T204	:	'Tupolev Tu-204 / Tu-214',
TB20	:	'Socata TB-20 Trinidad',
TL20	:	'TL Ultralight TL-96 Star / TL-2000 Sting',
TRF1	:	'Team Rocket F1',
TRIS	:	'Pilatus Britten-Norman BN-2A Mk III Trislander',
TWEN	:	'Tecnam P2010',
V22	:	'Bell Boeing V-22 Osprey',
WW24	:	'Israel Aircraft Industries 1124 Westwind',
Y12	:	'Harbin Yunshuji Y12',
YK40	:	'Yakovlev Yak-40',
YK42	:	'Yakovlev Yak-42',
YS11	:	'NAMC YS-11'
}
//..................................................................
objStrApi.town={
  'Севилья ':'Seville',  'Пиза':'Pisa',  'Kлуж':'Cluj-Napoca',  'Сучава':'Suceava',
  'Бари':'Bari',  'Закинтос':'Zakynthos',  'Кефалиния':'Kefaloniá',  'Бриндизи':'Brindisi',
  'Мальта':'Malta','Триест':'Trieste',
'Турин':'Turin', 'Генуя':'Genoa','Ламеция-Терме':'Lamezia Terme','Атланта':'Atlanta',
'Штутгарт':'Stuttgart','Малага':'Malaga','Стокгольм':'Stockholm','Сплит':'Split','Сантандер':'Satander',
'Порту':'Porto','Аликанте':'Alicante', 'Севилья':'Sevilla','Бильбао':'Bilbao','Сантьяго-де-Компостела':'Santiago de Compostela', 
'Пальма-де-Майорка':'Palma de Mallorca',  'Вроцлав':'Wrocław' , 'Нант':'Nantes','Гранада':'Granada','Клуж':'Cluj-Napoca',
'Дерби':'Derby','Пунта Кана':'Punta Cana','':'',
'Майами'  :'Miami',
'Брюссель':'Brussels' ,
'Тиват'   : 'Tivat' ,
'Ларнака' : 'Larnaca' ,
'Москва'  : 'Moscow',
'Родос'   : 'Rhodes',
'Кос'     : 'Greece',
'Ираклион': 'Heraklion',
 'Тира'     : 'Greece',
 'Шарм-эль-Шейх'     : 'Sharm el-Sheikh',
 'Катания'     : 'Catania',
 'Дубай'     : 'Dubai',
 'Болонья'     : 'Bolonia' ,
 'Бостон'     : 'Boston' ,
 'Пафос'     : 'Paphos' ,
 'Мемминген'     : 'Memmingen' ,
 'Бергамо'     : 'Bergamo' ,
 'Ираклион'     : 'Greece' ,
 'Родос'     : 'Rhodes' ,
 'Абу-Даби'     : 'Abu Dhabi' ,
 'Гонконг'     : 'Hong Kong' ,
 'Манама'     : 'Manama' ,
 'Марракеш'     : 'Marrakesh' ,
 'Манчестер'     : 'Manchester' ,
 'Салоники'     : 'Thessaloniki' ,
 'Ханья'     : 'Chania' ,
 'Йоханнесбург'     : 'Johannesburg' ,
 'Катовице'     : 'Katowice' ,
 'Йоханнесбург'     : 'Johannesburg' ,
 'Даламан'     : 'Izmir' ,
 'Любляна' :     'Ljubljana'  ,
 'Миконос':'Mykonos' ,
 
 
'Абиджан':'Abidjan',
'Адана':'Adana',
'Аддис-Абеба':'Addis Ababa',
'Аделаида':'Adelaide',
'Аккра':'Accra',
'Актюбинск':'Aktyubinsk/ Aktobe',
'Александрия':'Alexandria',
'Алжир':'Algiers',
'Алма-Ата (Алматы)':'Almaty',
'Амстердам':'Amsterdam',
'Анкара':'Ankara',
'Анталья':'Antalya',
'Антананариву':'Antananarivo',
'Антверпен':'Antwerp',
'Аньшань':'Anshan',
'Ахмадабад':'Ahmedabad',
'Астана':'Astana',
'Асунсьон':'Asuncion',
'Афины':'Athens',
'Ашхабад':'Ashgabat',
'Багдад':'Baghdad',
'Базель':'Basel',
'Баку':'Baku',
'Бангалор':'Bangalore',
'Бангкок':'Bangkok',
'Бандунг':'Bandung',
'Барранкилья':'Barranquilla',
'Барселона':'Barcelona',
'Батуми':'Batumi',
'Бейрут':'Beirut',
'Белград':'Belgrade',
'Белу-Оризонти':'Belo Horizonte',
'Берлин':'Berlin',
'Бирмингем':'Birmingham',
'Берн':'Berne',
'Бишкек':'Bishkek',
'Бобруйск':'Babruysk, Bobruysk',
'Богота':'Bogota',
'Бордо':'Bordeaux',
'Бразилиа':'Brasilia',
'Братислава':'Bratislava',
'Брест':'Brest',
'Брисбен':'Brisbane',
'Будапешт':'Budapest',
'Бухара':'Bukhara',
'Бухарест':'Bucharest',
'Буэнос-Айрес':'Buenos Aires',
'Бхопал':'Bhopal',
'Валенсия':'Valencia',
'Варна':'Varna',
'Варшава':'Warsaw',
'Вашингтон':'Washington',
'Веллингтон':'Wellington',
'Вена':'Vienna',
'Венеция':'Venice',
'Вильнюс':'Vilnius',
'Витебск':'Vitebsk',
'Гаага':'The Hague',
'Гавана':'Havana',
'Гамбург':'Hamburg',
'Гаосюн':'Kaohsiung',
'Гвадалахара':'Guadalajara',
'Гватемала':'Guatemala',
'Гданьск':'Gdansk',
'Гент':'Ghent',
'Гётеборг':'Gothenburg',
'Гирин':'Jilin',
'Глазго':'Glasgow',
'Гомель':'Gomel',
'Гродно':'Grodno, Hrodna',
'Гуанчжоу':'Guangzhou',
'Гуйян':'Guiyang',
'Гуаякиль':'Guayaquil',
'Дакар':'Dakar',
'Дакка':'Dhaka, Dacca',
'Даллас':'Dallas',
'Далянь':'Dalian',
'Дамаск':'Damascus',
'Дар-эс-Салам':'Dar es Salaam',
'Дели':'Delhi',
'Джайпур':'Jaipur',
'Джакарта':'Jakarta',
'Днепропетровск':'Dnipropetrovsk',
'Донецк':'Donetsk',
'Дрезден':'Dresden',
'Дублин':'Dublin',
'Дуала':'Douala',
'Душанбе':'Dushanbe',
'Дюссельдорф':'Duesseldorf',
'Ереван':'Yerevan',
'Женева':'Geneva',
'Житомир':'Zhytomyr',
'Загреб':'Zagreb',
'Запорожье':'Zaporizhia',
'Иерусалим':'Jerusalem',
'Индаур':'Indore',
'Ибадан':'Ibadan',
'Измир':'Izmir',
'Инсбрук':'Innsbruck',
'Инчхон':'Incheon',
'Иокогама':'Yokohama',
'Исламабад':'Islamabad',
'Исфахан':'Esfahan',
'Кавасаки':'Kawasaki',
'Каир':'Cairo',
'Кали':'Santiago de Cali',
'Калькутта':'Calcutta',
'Канны, Канн':'Cannes',
'Канпур':'Kanpur',
'Каракас':'Caracas',
'Караганда':'Karaganda',
'Карачи':'Karachi',
'Карловы Вары':'Karlovy Vary',
'Касабланка':'Casablanca',
'Каунас':'Kaunas',
'Кванджу':'Gwangju',
'Кёльн':'Cologne',
'Кесон-Сити':'Quezon City',
'Киев':'Kiev',
'Киншаса':'Kinshasa',
'Киото':'Kyoto',
'Кито':'Quito',
'Кишинёв':'Kishinev',
'Клайпеда':'Klaipeda',
'Кобе':'Kobe',
'Конакри':'Conakry',
'Копенгаген':'Copenhagen',
'Кордова':'Cordoba',
'Краков':'Krakow',
'Куала-Лумпур':'Kuala Lumpur',
'Куньмин':'Kunming',
'Лагос':'Lagos',
'Лакхнау':'Lucknow',
'Ланьчжоу':'Lanzhou',
'Лахор':'Lahore',
'Лейпциг':'Leipzig',
'Ливерпуль':'Liverpool',
'Лима':'Lima',
'Лимассол':'Limassol',
'Лион':'Lyons',
'Лиссабон':'Lisbon',
'Лозанна':'Lausanne',
'Лондон':'London',
'Лос-Анджелес':'Los Angeles',
'Луанда':'Luanda',
'Львов':'Lviv',
'Люксембург':'Luxembourg',
'Мадрид':'Madrid',
'Манаус':'Manaus',
'Манила':'Manila',
'Мапуту':'Maputo',
'Маракайбо':'Maracaibo',
'Марсель':'Marseilles',
'Медан':'Medan',
'Медельин':'Medellin',
'Мельбурн':'Melbourne',
'Мехико':'Mexico',
'Мешхед':'Mashhad',
'Милан':'Milan',
'Минск':'Minsk',
'Могилёв':'Mahilyow',
'Монреаль':'Montreal',
'Монтевидео':'Montevideo',
'Монтеррей':'Monterrey',
'Мумбаи':'Mumbai',
'Мюнхен':'Munich',
'Нагоя':'Nagoya',
'Нагпур':'Nagpur',
'Найроби':'Nairobi',
'Нанкин':'Nanjing',
'Наньчан':'Nanchang',
'Нарва':'Narva',
'Неаполь':'Naples',
'Никосия':'Nicosia',
'Нью-Йорк':'New York',
'Одесса':'Odessa',
'Осака':'Osaka',
'Осло':'Oslo',
'Оттава':'Ottawa',
'Палембанг':'Palembang',
'Париж':'Paris',
'Пекин':'Beijing',
'Перт':'Perth',
'Познань':'Poznan',
'Порту-Алегри':'Porto Alegre',
'Потсдам':'Potsdam',
'Прага':'Prague',
'Пуна':'Pune',
'Пусан':'Busan',
'Пхеньян':'Pyongyang',
'Ресифи':'Recife',
'Рига':'Riga',
'Рим':'Rome',
'Рио-де-Жанейро':'Rio (de) Janeiro',
'Роттердам':'Rotterdam',
'Салвадор':'Salvador',
'Самарканд':'Samarkand',
'Сан-Диего':'San Diego',
'Сан-Паулу':'Sao Paulo',
'Сан-Франциско':'San Francisco',
'Санто-Доминго':'Santo Domingo',
'Сантьяго':'Santiago',
'Саппоро':'Sapporo',
'Севастополь':'Sevastopol',
'Сеул':'Seoul',
'Сиань':'Xi’an',
'Сидней':'Sydney',
'Симферополь':'Simferopol',
'Сингапур':'Singapore',
'Солт-Лейк-Сити':'Salt Lake City',
'София':'Sofia',
'Стамбул':'Istanbul',
'Сурабая':'Surabaya',
'Сурат':'Surat',
'Тайбэй':'Taipei',
'Тайюань':'Taiyuan',
'Таллин (Таллинн)':'Tallinn',
'Таншань':'Tangshan',
'Тарту':'Tartu',
'Ташкент':'Tashkent',
'Тбилиси':'Tbilisi',
'Тебриз':'Tabriz',
'Тегеран':'Teh(e)ran',
'Тель-Авив':'Tel Aviv',
'Тирасполь':'Tiraspol',
'Токио':'Tokyo',
'Торонто':'Toronto',
'Тулуза':'Toulouse',
'Тэгу':'Daegu, Taegu',
'Тэджон':'Daejeon',
'Тяньцзинь':'Tianjin',
'Урумчи':'Urumchi',
'Утрехт':'Utrecht',
'Ухань':'Wuhan',
'Филадельфия':'Philadelphia',
'Финикс':'Phoenix',
'Флоренция':'Florence',
'Франкфурт-на-Майне':'Frankfurt',
'Франкфурт-на-Одере':'Frankfurt on the Oder',
'Фукуока':'Fukuoka',
'Фушунь':'Fushun',
'Хайфа':'Haifa',
'Халеб':'Aleppo',
'Ханой':'Hanoi',
'Ханчжоу':'Hangzhou',
'Хараре':'Harare',
'Харбин':'Harbin',
'Харьков':'Kharkiv',
'Хельсинки':'Helsinki',
'Хиросима':'Hiroshima',
'Хошимин':'Ho Chi Minh',
'Хьюстон':'Houston',
'Цзинань':'Jinan',
'Цзыбо':'Zibo',
'Циндао':'Qingdao',
'Цицикар':'Qiqihar',
'Цюрих':'Zurich',
'Чаньчунь':'Changchun',
'Чанша':'Changsha',
'Чикаго':'Chicago',
'Читтагонг':'Chittagong',
'Чунцин':'Chongqing',
'Чэнду':'Chengdu',
'Шанхай':'Shanghai',
'Шымкент':'Shymkent',
'Шэньян':'Shenyang',
'Щецин':'Szczecin',
'Эйлат':'Eilat',
'Эйндховен':'Eindhoven',
'Эль-Гиза':'Giza',
'Эль-Кувейт':'Kuwait',
'Эр-Рияд':'Riyadh',
'Ю':'',
'Юрмала':'Jurmala',
'Янгон':'Yangon, Rangoon'
}


